-- ==========================================================================
-- Generated by schemagen — do not edit manually
-- ==========================================================================

-- Dropdown/enum header definitions
CREATE TABLE IF NOT EXISTS constant_header (
    id                                   VARCHAR(60)   NOT NULL,
    caption                              VARCHAR(80)   NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dropdown/enum values for each constant header
CREATE TABLE IF NOT EXISTS constant_value (
    constant_id                          VARCHAR(60)   NOT NULL,
    value                                VARCHAR(80)   NOT NULL,
    caption                              VARCHAR(80)   NOT NULL,
    PRIMARY KEY (constant_id, value),
    CONSTRAINT constant_values FOREIGN KEY (constant_id) REFERENCES constant_header(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Maps constant domains to table columns
CREATE TABLE IF NOT EXISTS constant_lookup (
    constant_id                          VARCHAR(60)   NOT NULL,
    table_name                           VARCHAR(60)   NOT NULL,
    column_name                          VARCHAR(60)   NOT NULL,
    PRIMARY KEY (constant_id, table_name, column_name),
    CONSTRAINT constant_lookups FOREIGN KEY (constant_id) REFERENCES constant_header(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Controls FK display behavior in the UI
CREATE TABLE IF NOT EXISTS foreign_key_lookup (
    constraint_name                      VARCHAR(60)   NOT NULL,
    lookup_style                         CHAR(1)       NOT NULL,
    display_column                       VARCHAR(60)   NOT NULL,
    PRIMARY KEY (constraint_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Metadata-driven REST API definitions
CREATE TABLE IF NOT EXISTS rest_api_header (
    id                                   VARCHAR(80)   NOT NULL,
    version                              VARCHAR(20)   NOT NULL DEFAULT 'v1',
    master_table                         VARCHAR(60)   NOT NULL,
    is_active                            TINYINT(1)    NOT NULL DEFAULT 1,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Child relations for REST APIs
CREATE TABLE IF NOT EXISTS rest_api_child (
    api_id                               VARCHAR(80)   NOT NULL,
    seq                                  INT           NOT NULL,
    parent_seq                           INT           NOT NULL DEFAULT 0,
    constraint_name                      VARCHAR(60)   NOT NULL,
    PRIMARY KEY (api_id, seq),
    CONSTRAINT rest_api_children FOREIGN KEY (api_id) REFERENCES rest_api_header(id),
    CONSTRAINT rest_api_lookups FOREIGN KEY (constraint_name) REFERENCES foreign_key_lookup(constraint_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX idx_rest_api_child_fk ON rest_api_child(constraint_name);

-- Report definitions
CREATE TABLE IF NOT EXISTS rest_report_header (
    id                                   VARCHAR(80)   NOT NULL,
    version                              VARCHAR(20)   NOT NULL DEFAULT 'v1',
    query_name                           VARCHAR(60)   NOT NULL,
    description                          TEXT          NOT NULL,
    is_active                            TINYINT(1)    NOT NULL DEFAULT 1,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Report parameter definitions
CREATE TABLE IF NOT EXISTS rest_report_param (
    report_id                            VARCHAR(80)   NOT NULL,
    seq                                  INT           NOT NULL,
    param_name                           VARCHAR(20)   NOT NULL,
    data_type                            VARCHAR(20)   NOT NULL DEFAULT 'string',
    constant_id                          VARCHAR(60)  ,
    PRIMARY KEY (report_id, seq),
    CONSTRAINT rest_report_params FOREIGN KEY (report_id) REFERENCES rest_report_header(id),
    CONSTRAINT rest_report_param_constants FOREIGN KEY (constant_id) REFERENCES constant_header(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Maps tables to their PostgreSQL sequences
CREATE TABLE IF NOT EXISTS table_sequence_usage (
    table_name                           VARCHAR(32)   NOT NULL,
    column_name                          VARCHAR(32)   NOT NULL,
    sequence_name                        VARCHAR(32)   NOT NULL,
    PRIMARY KEY (table_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Navigation menu structure
CREATE TABLE IF NOT EXISTS application_menu (
    id                                   VARCHAR(30)   NOT NULL,
    caption                              VARCHAR(80)   NOT NULL,
    display_order                        INT           NOT NULL,
    is_active                            TINYINT(1)    NOT NULL DEFAULT 1,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Menu items with REST API links
CREATE TABLE IF NOT EXISTS application_menu_item (
    menu_id                              VARCHAR(30)   NOT NULL,
    item_id                              VARCHAR(30)   NOT NULL,
    caption                              TEXT          NOT NULL,
    display_order                        INT           NOT NULL,
    rest_uri                             VARCHAR(255)  NOT NULL,
    is_active                            TINYINT(1)    NOT NULL DEFAULT 1,
    filter_on_list                       TINYINT(1)    NOT NULL DEFAULT 0,
    PRIMARY KEY (menu_id, item_id),
    CONSTRAINT application_menu_items FOREIGN KEY (menu_id) REFERENCES application_menu(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- RBAC authorization object definitions
CREATE TABLE IF NOT EXISTS authorization_object (
    id                                   VARCHAR(30)   NOT NULL,
    caption                              VARCHAR(80)   NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Actions available on each authorization object
CREATE TABLE IF NOT EXISTS authorization_object_action (
    authorization_object_id              VARCHAR(30)   NOT NULL,
    action                               VARCHAR(30)   NOT NULL,
    caption                              VARCHAR(80)   NOT NULL,
    PRIMARY KEY (authorization_object_id, action),
    CONSTRAINT authorization_object_actions FOREIGN KEY (authorization_object_id) REFERENCES authorization_object(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Background worker registration and heartbeat
CREATE TABLE IF NOT EXISTS service_registry (
    service_name                         VARCHAR(16)   NOT NULL,
    started_at                           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    hostname                             VARCHAR(64)   NOT NULL,
    pid                                  BIGINT        NOT NULL,
    status                               CHAR(1)       NOT NULL,
    last_heartbeat                       DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (service_name, started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Country reference table
CREATE TABLE IF NOT EXISTS country (
    id                                   CHAR(2)       NOT NULL,
    caption                              VARCHAR(100)  NOT NULL,
    currency                             CHAR(3)       NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- State/province reference table
CREATE TABLE IF NOT EXISTS state (
    country_id                           CHAR(2)       NOT NULL,
    id                                   CHAR(2)       NOT NULL,
    caption                              VARCHAR(100)  NOT NULL,
    PRIMARY KEY (country_id, id),
    CONSTRAINT states FOREIGN KEY (country_id) REFERENCES country(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- County reference table
CREATE TABLE IF NOT EXISTS county (
    country_id                           CHAR(2)       NOT NULL,
    state_id                             CHAR(2)       NOT NULL,
    id                                   VARCHAR(100)  NOT NULL,
    PRIMARY KEY (country_id, state_id, id),
    CONSTRAINT counties FOREIGN KEY (country_id, state_id) REFERENCES state(country_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Authorization roles
CREATE TABLE IF NOT EXISTS authorization_role (
    id                                   VARCHAR(30)   NOT NULL,
    caption                              VARCHAR(80)   NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Role-based permission assignments
CREATE TABLE IF NOT EXISTS authorization_role_permission (
    role_id                              VARCHAR(30)   NOT NULL,
    authorization_object_id              VARCHAR(30)   NOT NULL,
    action                               VARCHAR(30)   NOT NULL,
    low_limit                            VARCHAR(80)   NOT NULL,
    high_limit                           VARCHAR(80)  ,
    bypass_scope                         TINYINT(1)    NOT NULL DEFAULT 0,
    is_active                            TINYINT(1)    NOT NULL DEFAULT 1,
    PRIMARY KEY (role_id, authorization_object_id, action, low_limit),
    CONSTRAINT authorization_role_permissions FOREIGN KEY (role_id) REFERENCES authorization_role(id),
    CONSTRAINT permitted_object_action FOREIGN KEY (authorization_object_id, action) REFERENCES authorization_object_action(authorization_object_id, action)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Configurable password and login policies
CREATE TABLE IF NOT EXISTS user_account_policy (
    id                                   VARCHAR(30)   NOT NULL,
    policy_value                         INT          ,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- User accounts with authentication credentials
CREATE TABLE IF NOT EXISTS user_account (
    id                                   BIGINT        NOT NULL,
    first_name                           VARCHAR(80)   NOT NULL,
    last_name                            VARCHAR(80)   NOT NULL,
    user_name                            VARCHAR(80)   NOT NULL,
    user_email                           VARCHAR(255) ,
    phone                                VARCHAR(20)  ,
    locale                               VARCHAR(10)  ,
    status                               CHAR(1)       NOT NULL,
    passtext                             VARCHAR(128) ,
    passdate                             DATETIME     ,
    login_attempts                       SMALLINT      NOT NULL DEFAULT 0,
    last_login_attempt                   DATETIME     ,
    lock_time                            DATETIME     ,
    twofa_enabled                        TINYINT(1)    DEFAULT 0,
    twofa_method                         CHAR(1)      ,
    twofa_secret                         VARCHAR(128) ,
    twofa_backup_codes                   TEXT         ,
    twofa_enabled_at                     DATETIME     ,
    twofa_last_step                      BIGINT        NOT NULL DEFAULT 0,
    deleted_at                           DATETIME     ,
    single_device_session                TINYINT(1)    NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE UNIQUE INDEX user_account_email_uq ON user_account(user_email);
CREATE UNIQUE INDEX user_account_phone_uq ON user_account(phone);

-- User-to-role assignments
CREATE TABLE IF NOT EXISTS user_permission (
    user_id                              BIGINT        NOT NULL,
    role_id                              VARCHAR(30)   NOT NULL,
    begda                                DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    endda                                DATETIME     ,
    PRIMARY KEY (user_id, role_id, begda),
    CONSTRAINT user_permissions FOREIGN KEY (user_id) REFERENCES user_account(id),
    CONSTRAINT permitted_users FOREIGN KEY (role_id) REFERENCES authorization_role(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX idx_user_permission_role ON user_permission(role_id);

-- Login audit trail
CREATE TABLE IF NOT EXISTS user_account_history (
    user_id                              BIGINT        NOT NULL,
    action_time                          DATETIME      NOT NULL,
    action_type                          CHAR(1)       NOT NULL,
    status                               CHAR(1)       NOT NULL,
    object_name                          VARCHAR(80)  ,
    client_address                       VARCHAR(15)  ,
    PRIMARY KEY (user_id, action_time),
    CONSTRAINT user_historic_actions FOREIGN KEY (user_id) REFERENCES user_account(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Pending user registrations, password reset tokens, and 2FA login tokens
CREATE TABLE IF NOT EXISTS user_registration (
    user_email                           VARCHAR(255)  NOT NULL,
    confirmation                         INT           NOT NULL,
    payload                              TEXT         ,
    status                               CHAR(1)       NOT NULL DEFAULT 'P',
    created_at                           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_at                         DATETIME     ,
    user_id                              BIGINT       ,
    attempts                             INT           NOT NULL DEFAULT 0,
    PRIMARY KEY (user_email, confirmation)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Multi-tenant business partner entity — shared core only (id + caption). Projects create separate tables for domain-specific extensions (e.g. partner_profile, partner_branding).
CREATE TABLE IF NOT EXISTS business_partner (
    id                                   BIGINT        NOT NULL,
    caption                              VARCHAR(200)  NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Associates users with business partners
CREATE TABLE IF NOT EXISTS partner_user (
    partner_id                           BIGINT        NOT NULL,
    user_id                              BIGINT        NOT NULL,
    begda                                DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    endda                                DATETIME     ,
    PRIMARY KEY (partner_id, user_id, begda),
    CONSTRAINT partner_users FOREIGN KEY (partner_id) REFERENCES business_partner(id),
    CONSTRAINT user_partners FOREIGN KEY (user_id) REFERENCES user_account(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX idx_partner_user_user ON partner_user(user_id);

-- Business partner addresses
CREATE TABLE IF NOT EXISTS partner_address (
    partner_id                           BIGINT        NOT NULL,
    address                              VARCHAR(200)  NOT NULL,
    city                                 VARCHAR(80)  ,
    country                              CHAR(2)      ,
    state                                CHAR(2)      ,
    zipcode                              VARCHAR(10)  ,
    phone                                VARCHAR(20)  ,
    latitude                             DECIMAL(10,7),
    longitude                            DECIMAL(10,7),
    PRIMARY KEY (partner_id, address),
    CONSTRAINT partner_addresses FOREIGN KEY (partner_id) REFERENCES business_partner(id),
    CONSTRAINT partner_address_countries FOREIGN KEY (country) REFERENCES country(id),
    CONSTRAINT partner_address_states FOREIGN KEY (country, state) REFERENCES state(country_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Partner website domains
CREATE TABLE IF NOT EXISTS partner_domain (
    partner_id                           BIGINT        NOT NULL,
    domain_url                           VARCHAR(255)  NOT NULL,
    is_primary                           TINYINT(1)    NOT NULL DEFAULT 0,
    created_at                           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (partner_id, domain_url),
    CONSTRAINT partner_domains FOREIGN KEY (partner_id) REFERENCES business_partner(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Per-column UI/CRUD display overrides (mode, field width, textarea rows)
CREATE TABLE IF NOT EXISTS column_display_attribute (
    table_name                           VARCHAR(63)   NOT NULL,
    column_name                          VARCHAR(63)   NOT NULL,
    display_mode                         CHAR(1)      ,
    display_width                        INT          ,
    display_rows                         INT          ,
    PRIMARY KEY (table_name, column_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- JWT refresh tokens
CREATE TABLE IF NOT EXISTS user_refresh_token (
    id                                   BIGINT        NOT NULL,
    user_id                              BIGINT        NOT NULL,
    token_hash                           VARCHAR(128)  NOT NULL,
    expires_at                           DATETIME      NOT NULL,
    revoked_at                           DATETIME     ,
    created_at                           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT user_refresh_tokens FOREIGN KEY (user_id) REFERENCES user_account(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX idx_refresh_token_hash ON user_refresh_token(token_hash);

-- Trusted devices for 2FA bypass; device_fingerprint holds hex SHA256 of a server-minted secret kept in an HttpOnly cookie (never the raw secret).
CREATE TABLE IF NOT EXISTS user_trusted_device (
    id                                   BIGINT        NOT NULL,
    user_id                              BIGINT        NOT NULL,
    device_fingerprint                   VARCHAR(128)  NOT NULL,
    device_name                          VARCHAR(200) ,
    trusted_at                           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at                           DATETIME      NOT NULL,
    last_seen_at                         DATETIME     ,
    PRIMARY KEY (id),
    CONSTRAINT user_trusted_devices FOREIGN KEY (user_id) REFERENCES user_account(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX idx_trusted_device_user ON user_trusted_device(user_id, device_fingerprint);

-- API keys for public API access with rotation support
CREATE TABLE IF NOT EXISTS api_key (
    id                                   BIGINT        NOT NULL,
    partner_id                           BIGINT        NOT NULL,
    key_name                             VARCHAR(100)  NOT NULL,
    key_prefix                           CHAR(8)       NOT NULL,
    key_hash                             CHAR(64)      NOT NULL,
    scopes                               VARCHAR(500)  NOT NULL DEFAULT 'query',
    is_active                            TINYINT(1)    NOT NULL DEFAULT 1,
    created_at                           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at                           DATETIME     ,
    last_used_at                         DATETIME     ,
    user_id                              BIGINT       ,
    rotated_at                           DATETIME     ,
    grace_expires_at                     DATETIME     ,
    PRIMARY KEY (id),
    CONSTRAINT api_key_partners FOREIGN KEY (partner_id) REFERENCES business_partner(id),
    CONSTRAINT api_key_users FOREIGN KEY (user_id) REFERENCES user_account(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE UNIQUE INDEX idx_api_key_hash ON api_key(key_hash);
CREATE INDEX idx_api_key_partner ON api_key(partner_id);

-- One-time password codes for phone/email verification
CREATE TABLE IF NOT EXISTS user_otp (
    id                                   BIGINT        NOT NULL,
    user_id                              BIGINT        NOT NULL,
    code                                 VARCHAR(6)    NOT NULL,
    purpose                              VARCHAR(20)   NOT NULL,
    expires_at                           DATETIME      NOT NULL,
    attempts                             INT           NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT user_otps FOREIGN KEY (user_id) REFERENCES user_account(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Social login provider links (Google, Apple)
CREATE TABLE IF NOT EXISTS user_social_provider (
    user_id                              BIGINT        NOT NULL,
    provider                             VARCHAR(20)   NOT NULL,
    provider_id                          VARCHAR(255)  NOT NULL,
    PRIMARY KEY (user_id, provider),
    CONSTRAINT user_social_providers FOREIGN KEY (user_id) REFERENCES user_account(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Versioned privacy/terms/consent policy text registered for audit trail
CREATE TABLE IF NOT EXISTS consent_policy (
    id                                   BIGINT        NOT NULL,
    policy_type                          VARCHAR(30)   NOT NULL,
    region                               VARCHAR(10)   NOT NULL DEFAULT 'global',
    version                              VARCHAR(64)   NOT NULL,
    language                             VARCHAR(8)    NOT NULL DEFAULT 'en',
    content_url                          VARCHAR(500)  NOT NULL,
    content_sha256                       VARCHAR(64)   NOT NULL,
    effective_from                       DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deprecated_at                        DATETIME     ,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE UNIQUE INDEX consent_policy_uq ON consent_policy(policy_type, region, version, language);

-- Per-user consent decisions with full audit trail for PIPEDA/GDPR
CREATE TABLE IF NOT EXISTS consent_event (
    id                                   BIGINT        NOT NULL,
    user_id                              BIGINT       ,
    email_hash                           VARCHAR(64)  ,
    consent_type                         VARCHAR(30)   NOT NULL,
    consented                            TINYINT(1)    NOT NULL,
    policy_id                            BIGINT        NOT NULL,
    event_ref                            VARCHAR(64)  ,
    region                               VARCHAR(10)   NOT NULL,
    client_ip                            VARCHAR(45)  ,
    client_user_agent                    VARCHAR(500) ,
    created_at                           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT consent_event_policies FOREIGN KEY (policy_id) REFERENCES consent_policy(id),
    CONSTRAINT consent_event_users FOREIGN KEY (user_id) REFERENCES user_account(id),
    CONSTRAINT consent_event_identity CHECK (user_id IS NOT NULL OR email_hash IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX idx_consent_event_user ON consent_event(user_id, consent_type);
CREATE INDEX idx_consent_event_email ON consent_event(email_hash, consent_type);

-- Mobile device push-notification tokens (FCM / APNs via FCM)
CREATE TABLE IF NOT EXISTS device_token (
    id                                   BIGINT        NOT NULL,
    user_id                              BIGINT        NOT NULL,
    platform                             CHAR(1)       NOT NULL,
    token                                TEXT          NOT NULL,
    app_version                          VARCHAR(32)  ,
    device_model                         VARCHAR(64)  ,
    is_active                            TINYINT(1)    NOT NULL DEFAULT 1,
    created_at                           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at                         DATETIME     ,
    PRIMARY KEY (id),
    CONSTRAINT device_token_users FOREIGN KEY (user_id) REFERENCES user_account(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE UNIQUE INDEX device_token_user_token_uq ON device_token(user_id, token);
CREATE INDEX idx_device_token_user_active ON device_token(user_id, is_active);

-- OAuth 2.1 registered clients (Dynamic Client Registration)
CREATE TABLE IF NOT EXISTS oauth_client (
    id                                   BIGINT        NOT NULL,
    client_id                            VARCHAR(64)   NOT NULL,
    secret_hash                          VARCHAR(64)  ,
    client_name                          VARCHAR(200) ,
    redirect_uris                        VARCHAR(2000) NOT NULL,
    grant_types                          VARCHAR(500)  NOT NULL,
    scopes                               VARCHAR(1000),
    token_auth_method                    VARCHAR(40)   NOT NULL DEFAULT 'none',
    created_at                           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE UNIQUE INDEX idx_oauth_client_client_id ON oauth_client(client_id);

-- Subscription plans (catalog). Per-interval prices live in subscription_plan_price.
CREATE TABLE IF NOT EXISTS subscription_plan (
    id                                   VARCHAR(20)   NOT NULL,
    caption                              VARCHAR(80)   NOT NULL,
    is_active                            TINYINT(1)    NOT NULL DEFAULT 1,
    currency                             CHAR(3)       NOT NULL DEFAULT 'USD',
    activation_mode                      CHAR(1)       NOT NULL DEFAULT 'A',
    trial_days                           INT          ,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Single-use OAuth 2.1 authorization codes; partner_id is a denormalized snapshot for quota attribution
CREATE TABLE IF NOT EXISTS oauth_authorization_code (
    id                                   BIGINT        NOT NULL,
    code_hash                            CHAR(64)      NOT NULL,
    client_id                            VARCHAR(64)   NOT NULL,
    user_id                              BIGINT        NOT NULL,
    partner_id                           BIGINT       ,
    scopes                               VARCHAR(1000),
    redirect_uri                         VARCHAR(2000) NOT NULL,
    code_challenge                       VARCHAR(128)  NOT NULL,
    code_challenge_method                VARCHAR(10)   NOT NULL,
    resource                             VARCHAR(500) ,
    expires_at                           DATETIME      NOT NULL,
    created_at                           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT oauth_authorization_code_user FOREIGN KEY (user_id) REFERENCES user_account(id),
    CONSTRAINT oauth_authorization_code_client FOREIGN KEY (client_id) REFERENCES oauth_client(client_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE UNIQUE INDEX idx_oauth_code_hash ON oauth_authorization_code(code_hash);

-- Per-offer price points for a plan. Three independent axes — billing_cycle (how often charged), term_count×term_type (the commitment), and amount_minor (price for ONE term_type unit). The same plan can offer e.g. monthly, annual-paid-monthly, and annual-paid-once as distinct rows with their own provider_price_id.
CREATE TABLE IF NOT EXISTS subscription_plan_price (
    plan_id                              VARCHAR(20)   NOT NULL,
    billing_cycle                        CHAR(1)       NOT NULL,
    term_count                           INT           NOT NULL DEFAULT 1,
    term_type                            CHAR(1)       NOT NULL DEFAULT 'M',
    amount_minor                         BIGINT        NOT NULL,
    currency                             CHAR(3)       NOT NULL DEFAULT 'USD',
    provider_price_id                    VARCHAR(64)  ,
    PRIMARY KEY (plan_id, billing_cycle, term_type, term_count),
    CONSTRAINT subscription_plan_prices FOREIGN KEY (plan_id) REFERENCES subscription_plan(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Quota-tracked resources (domains, API calls, etc.)
CREATE TABLE IF NOT EXISTS subscription_resource (
    id                                   VARCHAR(20)   NOT NULL,
    table_name                           VARCHAR(32)  ,
    status_column                        VARCHAR(32)  ,
    status_value                         VARCHAR(80)  ,
    date_column                          VARCHAR(32)  ,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- OAuth 2.1 refresh tokens (hashed) with rotation family for reuse-detection; partner_id is a denormalized snapshot
CREATE TABLE IF NOT EXISTS oauth_refresh_token (
    id                                   BIGINT        NOT NULL,
    token_hash                           CHAR(64)      NOT NULL,
    family_id                            VARCHAR(64)   NOT NULL,
    client_id                            VARCHAR(64)   NOT NULL,
    user_id                              BIGINT        NOT NULL,
    partner_id                           BIGINT       ,
    scopes                               VARCHAR(1000),
    resource                             VARCHAR(500) ,
    expires_at                           DATETIME      NOT NULL,
    revoked_at                           DATETIME     ,
    created_at                           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT oauth_refresh_token_user FOREIGN KEY (user_id) REFERENCES user_account(id),
    CONSTRAINT oauth_refresh_token_client FOREIGN KEY (client_id) REFERENCES oauth_client(client_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE UNIQUE INDEX idx_oauth_refresh_hash ON oauth_refresh_token(token_hash);
CREATE INDEX idx_oauth_refresh_family ON oauth_refresh_token(family_id);
CREATE INDEX idx_oauth_refresh_user ON oauth_refresh_token(user_id);

-- Resource limits per subscription plan
CREATE TABLE IF NOT EXISTS subscription_quota (
    plan_id                              VARCHAR(20)   NOT NULL,
    resource_id                          VARCHAR(20)   NOT NULL,
    max_value                            BIGINT        NOT NULL,
    period_type                          CHAR(1)       NOT NULL DEFAULT 'M',
    PRIMARY KEY (plan_id, resource_id),
    CONSTRAINT subscription_quotas FOREIGN KEY (plan_id) REFERENCES subscription_plan(id),
    CONSTRAINT sub_resources_quotas FOREIGN KEY (resource_id) REFERENCES subscription_resource(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- OAuth / API-key credentials for partner connections to external providers
CREATE TABLE IF NOT EXISTS partner_credential (
    id                                   BIGINT        NOT NULL,
    partner_id                           BIGINT        NOT NULL,
    entity_id                            BIGINT        NOT NULL DEFAULT 0,
    provider                             VARCHAR(30)   NOT NULL,
    connection_type                      CHAR(1)       NOT NULL DEFAULT 'O',
    cred_ref                             TEXT          NOT NULL,
    api_endpoint                         VARCHAR(255) ,
    status                               CHAR(1)       NOT NULL DEFAULT 'A',
    rev                                  INT           NOT NULL DEFAULT 0,
    lease_until                          DATETIME     ,
    issued_at                            DATETIME     ,
    last_checked                         DATETIME     ,
    created_at                           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT partner_credential_partners FOREIGN KEY (partner_id) REFERENCES business_partner(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE UNIQUE INDEX partner_credential_uq ON partner_credential(partner_id, entity_id, provider);

-- Optional add-on features with separate pricing
CREATE TABLE IF NOT EXISTS subscription_addon (
    id                                   VARCHAR(20)   NOT NULL,
    caption                              VARCHAR(80)   NOT NULL,
    max_value                            BIGINT        NOT NULL,
    is_active                            TINYINT(1)    NOT NULL DEFAULT 1,
    monthly_cost                         DECIMAL(18,2) NOT NULL,
    currency                             CHAR(3)       NOT NULL DEFAULT 'USD',
    billing_cycle                        CHAR(1)       NOT NULL DEFAULT 'M',
    term_count                           INT           NOT NULL DEFAULT 1,
    term_type                            CHAR(1)       NOT NULL DEFAULT 'M',
    description                          VARCHAR(255) ,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Single-use, TTL-bounded nonces (OAuth connect-state, JWT handoff). Natural key, no sequence.
CREATE TABLE IF NOT EXISTS auth_nonce (
    nonce                                VARCHAR(64)   NOT NULL,
    purpose                              VARCHAR(20)   NOT NULL,
    payload                              TEXT          NOT NULL,
    created_at                           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (nonce)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Active plan subscriptions per business partner
CREATE TABLE IF NOT EXISTS partner_plan_subscription (
    partner_id                           BIGINT        NOT NULL,
    plan_id                              VARCHAR(20)   NOT NULL,
    begda                                DATETIME      NOT NULL,
    endda                                DATETIME     ,
    monthly_cost                         DECIMAL(18,2) NOT NULL,
    currency                             CHAR(3)       NOT NULL,
    status                               CHAR(1)       NOT NULL,
    auto_renew                           TINYINT(1)    NOT NULL DEFAULT 1,
    provider_subscription_id             VARCHAR(64)  ,
    billing_cycle                        CHAR(1)      ,
    term_count                           INT          ,
    term_type                            CHAR(1)      ,
    amount_minor                         BIGINT       ,
    renewal_date                         DATETIME     ,
    next_charge_date                     DATETIME     ,
    cancelled_at                         DATETIME     ,
    effective_cancel_date                DATETIME     ,
    trial_end                            DATETIME     ,
    seats                                INT          ,
    PRIMARY KEY (partner_id, plan_id, begda),
    CONSTRAINT partner_plan_subscriptions FOREIGN KEY (partner_id) REFERENCES business_partner(id),
    CONSTRAINT partner_subscriptions_plan FOREIGN KEY (plan_id) REFERENCES subscription_plan(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX idx_partner_plan_subscription_provider_sub ON partner_plan_subscription(provider_subscription_id);

-- Active add-on subscriptions per business partner
CREATE TABLE IF NOT EXISTS partner_addon_subscription (
    partner_id                           BIGINT        NOT NULL,
    addon_id                             VARCHAR(20)   NOT NULL,
    auto_increase                        TINYINT(1)    NOT NULL DEFAULT 0,
    begda                                DATETIME      NOT NULL,
    endda                                DATETIME     ,
    monthly_cost                         DECIMAL(18,2) NOT NULL,
    currency                             CHAR(3)       NOT NULL,
    status                               CHAR(1)       NOT NULL,
    auto_renew                           TINYINT(1)    NOT NULL DEFAULT 1,
    billing_cycle                        CHAR(1)      ,
    term_count                           INT          ,
    term_type                            CHAR(1)      ,
    amount_minor                         BIGINT       ,
    renewal_date                         DATETIME     ,
    next_charge_date                     DATETIME     ,
    PRIMARY KEY (partner_id, addon_id, begda),
    CONSTRAINT partner_addon_subscriptions FOREIGN KEY (partner_id) REFERENCES business_partner(id),
    CONSTRAINT partner_subscriptions_addon FOREIGN KEY (addon_id) REFERENCES subscription_addon(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Resource usage tracking for quota enforcement
CREATE TABLE IF NOT EXISTS usage_ledger (
    partner_id                           BIGINT        NOT NULL,
    usage_time                           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resource_name                        VARCHAR(50)   NOT NULL,
    amount                               BIGINT        NOT NULL,
    notes                                VARCHAR(255) ,
    PRIMARY KEY (partner_id, usage_time),
    CONSTRAINT partner_usage_ledger FOREIGN KEY (partner_id) REFERENCES business_partner(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX idx_usage_ledger_quota ON usage_ledger(partner_id, resource_name, usage_time);

-- Raw inbound payment provider webhooks — idempotency + audit
CREATE TABLE IF NOT EXISTS payment_webhook_log (
    id                                   BIGINT        NOT NULL,
    provider                             VARCHAR(30)   NOT NULL,
    event_id                             VARCHAR(255)  NOT NULL,
    event_type                           VARCHAR(100)  NOT NULL,
    processing_status                    CHAR(1)       NOT NULL DEFAULT 'R',
    error_message                        TEXT         ,
    raw_payload                          TEXT         ,
    received_at                          DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at                         DATETIME     ,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE UNIQUE INDEX payment_webhook_log_uq ON payment_webhook_log(provider, event_id);

-- Stored payment methods per business partner (provider customer tokens)
CREATE TABLE IF NOT EXISTS payment_method (
    id                                   BIGINT        NOT NULL,
    partner_id                           BIGINT        NOT NULL,
    provider                             VARCHAR(30)   NOT NULL,
    provider_token                       VARCHAR(255)  NOT NULL,
    method_type                          VARCHAR(20)   NOT NULL,
    is_default                           TINYINT(1)    NOT NULL DEFAULT 0,
    created_at                           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT partner_payment_methods FOREIGN KEY (partner_id) REFERENCES business_partner(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX idx_payment_method_default ON payment_method(partner_id, is_default);

-- Completed/failed/refunded payment transactions per partner
CREATE TABLE IF NOT EXISTS payment_record (
    id                                   BIGINT        NOT NULL,
    partner_id                           BIGINT       ,
    provider                             VARCHAR(30)   NOT NULL,
    provider_payment_id                  VARCHAR(255) ,
    provider_event_type                  VARCHAR(100) ,
    amount                               DECIMAL(18,2) NOT NULL,
    currency                             CHAR(3)       NOT NULL,
    plan_id                              VARCHAR(20)  ,
    invoice_id                           BIGINT       ,
    payment_status                       CHAR(1)       NOT NULL,
    paid_at                              DATETIME     ,
    raw_payload                          TEXT         ,
    created_at                           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT partner_payment_records FOREIGN KEY (partner_id) REFERENCES business_partner(id),
    CONSTRAINT payment_record_plans FOREIGN KEY (plan_id) REFERENCES subscription_plan(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX idx_payment_record_partner ON payment_record(partner_id, paid_at);

-- Per (user, partner) bank account details for out-bound payouts.
-- Owned by keel/payout. Raw routing details live with the provider
-- (Airwallex / Stripe Connect / Wise); this row carries only the
-- provider handle plus tax/correspondence metadata.
CREATE TABLE IF NOT EXISTS user_bank_info (
    user_id                              BIGINT        NOT NULL,
    partner_id                           BIGINT        NOT NULL,
    country_code                         CHAR(2)       NOT NULL,
    currency                             CHAR(3)       NOT NULL,
    account_holder_name                  VARCHAR(200)  NOT NULL,
    billing_address                      TEXT          NOT NULL,
    tax_id_type                          CHAR(1)       NOT NULL,
    tax_id_encrypted                     BLOB          NOT NULL,
    provider                             CHAR(2)       NOT NULL,
    provider_account_id                  VARCHAR(100) ,
    provider_agreement                   TINYINT(1)    NOT NULL DEFAULT 0,
    provider_onboarded_at                DATETIME     ,
    created_at                           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, partner_id),
    CONSTRAINT user_bank_info_users FOREIGN KEY (user_id) REFERENCES user_account(id),
    CONSTRAINT user_bank_info_partners FOREIGN KEY (partner_id) REFERENCES business_partner(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX idx_user_bank_info_partner ON user_bank_info(partner_id);

-- Saved payment methods for end users (cards, wallets, bank accounts).
-- Distinct from `payment_method`, which is partner-scoped for SaaS
-- billing — this row is per (user_id), the consumer cards a user has
-- on file for in-bound payments. provider_token is the provider's
-- reusable handle (Stripe PaymentMethod id, SetupIntent id, etc.);
-- raw card numbers / IBANs / SWIFT never land here.
CREATE TABLE IF NOT EXISTS user_payment_method (
    id                                   BIGINT        NOT NULL,
    user_id                              BIGINT        NOT NULL,
    method_type                          VARCHAR(20)   NOT NULL,
    provider                             VARCHAR(30)   NOT NULL,
    provider_token                       VARCHAR(255)  NOT NULL,
    last_four                            VARCHAR(4)   ,
    brand                                VARCHAR(20)  ,
    expiry_month                         SMALLINT     ,
    expiry_year                          SMALLINT     ,
    currency                             CHAR(3)       NOT NULL DEFAULT 'USD',
    is_default                           TINYINT(1)    NOT NULL DEFAULT 0,
    created_at                           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT user_payment_method_users FOREIGN KEY (user_id) REFERENCES user_account(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX idx_user_payment_method_user ON user_payment_method(user_id, is_default);

-- Per-table custom actions surfaced as buttons in CRUD UIs. Each row
-- registers ONE action; the downstream application must also (a) seed
-- the matching authorization_object + authorization_object_action rows
-- so roles can grant access, and (b) register an HTTP handler at the
-- conventional URL POST /<rest_prefix>/<table_name>/<action_name>.
-- 
-- authorization_object.id mirrors the uppercased table name and
-- authorization_object_action.action mirrors the uppercased action_name
-- — gives each table its own action namespace so the same action name
-- ('assign', 'enable', 'calculate') can mean different things on
-- different tables without a shared auth dimension.
-- 
-- record_specific=TRUE  → button renders next to per-row edit/delete.
-- record_specific=FALSE → button renders next to the "New Record"
--                         control at the table-level toolbar.
-- 
-- Reserved action_name values that collide with generic CRUD subpaths
-- (list / get / post / delete / get-paginated) are rejected at REST
-- service boot.
CREATE TABLE IF NOT EXISTS table_action (
    table_name                           VARCHAR(80)   NOT NULL,
    action_name                          VARCHAR(30)   NOT NULL,
    caption                              VARCHAR(80)   NOT NULL,
    icon                                 VARCHAR(40)  ,
    record_specific                      TINYINT(1)    NOT NULL DEFAULT 0,
    action_kind                          CHAR(1)       NOT NULL DEFAULT 'P',
    method_name                          VARCHAR(80)  ,
    display_order                        SMALLINT      NOT NULL DEFAULT 10,
    confirm_message                      VARCHAR(200) ,
    PRIMARY KEY (table_name, action_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX idx_table_action_table ON table_action(table_name);

-- Billing invoices per partner (provider-issued or self-scheduled)
CREATE TABLE IF NOT EXISTS invoice (
    id                                   BIGINT        NOT NULL,
    partner_id                           BIGINT        NOT NULL,
    invoice_number                       VARCHAR(30)   NOT NULL,
    status                               CHAR(1)       NOT NULL DEFAULT 'D',
    subtotal                             DECIMAL(18,2) NOT NULL,
    tax                                  DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    total                                DECIMAL(18,2) NOT NULL,
    total_minor                          BIGINT        NOT NULL DEFAULT 0,
    currency                             CHAR(3)       NOT NULL DEFAULT 'USD',
    issued_at                            DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    due_at                               DATETIME     ,
    paid_at                              DATETIME     ,
    pdf_storage_path                     VARCHAR(500) ,
    provider_invoice_id                  VARCHAR(255) ,
    provider_charge_id                   VARCHAR(255) ,
    attempt_count                        INT           NOT NULL DEFAULT 0,
    next_attempt_at                      DATETIME     ,
    last_error                           TEXT         ,
    PRIMARY KEY (id),
    CONSTRAINT partner_invoices FOREIGN KEY (partner_id) REFERENCES business_partner(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE UNIQUE INDEX idx_invoice_number ON invoice(invoice_number);
CREATE INDEX idx_invoice_partner ON invoice(partner_id);

-- Line items for an invoice
CREATE TABLE IF NOT EXISTS invoice_line (
    invoice_id                           BIGINT        NOT NULL,
    seq                                  INT           NOT NULL,
    description                          VARCHAR(200)  NOT NULL,
    quantity                             INT           NOT NULL DEFAULT 1,
    unit_price                           DECIMAL(18,2) NOT NULL,
    amount                               DECIMAL(18,2) NOT NULL,
    PRIMARY KEY (invoice_id, seq),
    CONSTRAINT invoice_lines FOREIGN KEY (invoice_id) REFERENCES invoice(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Partner ↔ provider-customer token, one row per (partner, provider). Its own
-- table (not a method_type='customer' row in payment_method) so payment_method
-- holds only real chargeable methods. Used for billing-portal sessions and
-- recurring-invoice attribution (the reverse token→partner lookup).
CREATE TABLE IF NOT EXISTS partner_billing_customer (
    partner_id                           BIGINT        NOT NULL,
    provider                             VARCHAR(30)   NOT NULL,
    customer_token                       VARCHAR(255)  NOT NULL,
    created_at                           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (partner_id, provider),
    CONSTRAINT partner_billing_customers FOREIGN KEY (partner_id) REFERENCES business_partner(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE UNIQUE INDEX idx_partner_billing_customer_token ON partner_billing_customer(provider, customer_token);

-- Transactional outbox — events captured in the same tx as a domain write, then drained by a lease worker for reliable at-least-once delivery
CREATE TABLE IF NOT EXISTS outbox_event (
    id                                   BIGINT        NOT NULL,
    partner_id                           BIGINT       ,
    aggregate_type                       VARCHAR(64)   NOT NULL,
    aggregate_id                         VARCHAR(128)  NOT NULL,
    event_type                           VARCHAR(64)   NOT NULL,
    payload                              TEXT         ,
    status                               CHAR(1)       NOT NULL DEFAULT 'P',
    attempts                             INT           NOT NULL DEFAULT 0,
    available_at                         DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lease_until                          DATETIME     ,
    lease_token                          BIGINT       ,
    last_error                           TEXT         ,
    created_at                           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT outbox_event_partner FOREIGN KEY (partner_id) REFERENCES business_partner(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX idx_outbox_drain ON outbox_event(status, available_at);
CREATE INDEX idx_outbox_aggregate ON outbox_event(aggregate_type, aggregate_id);
