-- ==========================================================================
-- Generated by schemagen — do not edit manually
-- ==========================================================================

-- Dropdown/enum header definitions
CREATE TABLE IF NOT EXISTS constant_header (
    id                                   VARCHAR(60)   NOT NULL,
    caption                              VARCHAR(80)   NOT NULL,
    CONSTRAINT constant_header_pk PRIMARY KEY (id)
);

-- Dropdown/enum values for each constant header
CREATE TABLE IF NOT EXISTS constant_value (
    constant_id                          VARCHAR(60)   NOT NULL,
    value                                VARCHAR(80)   NOT NULL,
    caption                              VARCHAR(80)   NOT NULL,
    CONSTRAINT constant_value_pk PRIMARY KEY (constant_id, value)
);

-- Maps constant domains to table columns
CREATE TABLE IF NOT EXISTS constant_lookup (
    constant_id                          VARCHAR(60)   NOT NULL,
    table_name                           VARCHAR(60)   NOT NULL,
    column_name                          VARCHAR(60)   NOT NULL,
    CONSTRAINT constant_lookup_pk PRIMARY KEY (constant_id, table_name, column_name)
);

-- Controls FK display behavior in the UI
CREATE TABLE IF NOT EXISTS foreign_key_lookup (
    constraint_name                      VARCHAR(60)   NOT NULL,
    lookup_style                         CHAR(1)       NOT NULL,
    display_column                       VARCHAR(60)   NOT NULL,
    CONSTRAINT foreign_key_lookup_pk PRIMARY KEY (constraint_name)
);

-- Metadata-driven REST API definitions
CREATE TABLE IF NOT EXISTS rest_api_header (
    id                                   VARCHAR(80)   NOT NULL,
    version                              VARCHAR(20)   NOT NULL DEFAULT 'v1',
    master_table                         VARCHAR(60)   NOT NULL,
    is_active                            BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT rest_api_header_pk PRIMARY KEY (id)
);

-- Child relations for REST APIs
CREATE TABLE IF NOT EXISTS rest_api_child (
    api_id                               VARCHAR(80)   NOT NULL,
    seq                                  INTEGER       NOT NULL,
    parent_seq                           INTEGER       NOT NULL DEFAULT 0,
    constraint_name                      VARCHAR(60)   NOT NULL,
    CONSTRAINT rest_api_child_pk PRIMARY KEY (api_id, seq)
);
CREATE INDEX IF NOT EXISTS idx_rest_api_child_fk ON rest_api_child(constraint_name);

-- Report definitions
CREATE TABLE IF NOT EXISTS rest_report_header (
    id                                   VARCHAR(80)   NOT NULL,
    version                              VARCHAR(20)   NOT NULL DEFAULT 'v1',
    query_name                           VARCHAR(60)   NOT NULL,
    description                          TEXT          NOT NULL,
    is_active                            BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT rest_report_header_pk PRIMARY KEY (id)
);

-- Report parameter definitions
CREATE TABLE IF NOT EXISTS rest_report_param (
    report_id                            VARCHAR(80)   NOT NULL,
    seq                                  INTEGER       NOT NULL,
    param_name                           VARCHAR(20)   NOT NULL,
    data_type                            VARCHAR(20)   NOT NULL DEFAULT 'string',
    constant_id                          VARCHAR(60)  ,
    CONSTRAINT rest_report_param_pk PRIMARY KEY (report_id, seq)
);

-- Maps tables to their PostgreSQL sequences
CREATE TABLE IF NOT EXISTS table_sequence_usage (
    table_name                           VARCHAR(32)   NOT NULL,
    column_name                          VARCHAR(32)   NOT NULL,
    sequence_name                        VARCHAR(32)   NOT NULL,
    CONSTRAINT table_sequence_usage_pk PRIMARY KEY (table_name)
);

-- Navigation menu structure
CREATE TABLE IF NOT EXISTS application_menu (
    id                                   VARCHAR(30)   NOT NULL,
    caption                              VARCHAR(80)   NOT NULL,
    display_order                        INTEGER       NOT NULL,
    is_active                            BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT application_menu_pk PRIMARY KEY (id)
);

-- Menu items with REST API links
CREATE TABLE IF NOT EXISTS application_menu_item (
    menu_id                              VARCHAR(30)   NOT NULL,
    item_id                              VARCHAR(30)   NOT NULL,
    caption                              TEXT          NOT NULL,
    display_order                        INTEGER       NOT NULL,
    rest_uri                             VARCHAR(255)  NOT NULL,
    is_active                            BOOLEAN       NOT NULL DEFAULT TRUE,
    filter_on_list                       BOOLEAN       NOT NULL DEFAULT FALSE,
    CONSTRAINT application_menu_item_pk PRIMARY KEY (menu_id, item_id)
);

-- RBAC authorization object definitions
CREATE TABLE IF NOT EXISTS authorization_object (
    id                                   VARCHAR(30)   NOT NULL,
    caption                              VARCHAR(80)   NOT NULL,
    CONSTRAINT authorization_object_pk PRIMARY KEY (id)
);

-- Actions available on each authorization object
CREATE TABLE IF NOT EXISTS authorization_object_action (
    authorization_object_id              VARCHAR(30)   NOT NULL,
    action                               VARCHAR(30)   NOT NULL,
    caption                              VARCHAR(80)   NOT NULL,
    CONSTRAINT authorization_object_action_pk PRIMARY KEY (authorization_object_id, action)
);

-- Background worker registration and heartbeat
CREATE TABLE IF NOT EXISTS service_registry (
    service_name                         VARCHAR(16)   NOT NULL,
    started_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    hostname                             VARCHAR(64)   NOT NULL,
    pid                                  BIGINT        NOT NULL,
    status                               CHAR(1)       NOT NULL,
    last_heartbeat                       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT service_registry_pk PRIMARY KEY (service_name, started_at)
);

-- Country reference table
CREATE TABLE IF NOT EXISTS country (
    id                                   CHAR(2)       NOT NULL,
    caption                              VARCHAR(100)  NOT NULL,
    CONSTRAINT country_pk PRIMARY KEY (id)
);

-- State/province reference table
CREATE TABLE IF NOT EXISTS state (
    country_id                           CHAR(2)       NOT NULL,
    id                                   CHAR(2)       NOT NULL,
    caption                              VARCHAR(100)  NOT NULL,
    CONSTRAINT state_pk PRIMARY KEY (country_id, id)
);

-- County reference table
CREATE TABLE IF NOT EXISTS county (
    country_id                           CHAR(2)       NOT NULL,
    state_id                             CHAR(2)       NOT NULL,
    id                                   VARCHAR(100)  NOT NULL,
    CONSTRAINT county_pk PRIMARY KEY (country_id, state_id, id)
);

-- Authorization roles
CREATE TABLE IF NOT EXISTS authorization_role (
    id                                   VARCHAR(30)   NOT NULL,
    caption                              VARCHAR(80)   NOT NULL,
    CONSTRAINT authorization_role_pk PRIMARY KEY (id)
);

-- Role-based permission assignments
CREATE TABLE IF NOT EXISTS authorization_role_permission (
    role_id                              VARCHAR(30)   NOT NULL,
    authorization_object_id              VARCHAR(30)   NOT NULL,
    action                               VARCHAR(30)   NOT NULL,
    low_limit                            VARCHAR(80)   NOT NULL,
    high_limit                           VARCHAR(80)  ,
    bypass_scope                         BOOLEAN       NOT NULL DEFAULT FALSE,
    is_active                            BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT authorization_role_permission_pk PRIMARY KEY (role_id, authorization_object_id, action, low_limit)
);

-- Configurable password and login policies
CREATE TABLE IF NOT EXISTS user_account_policy (
    id                                   VARCHAR(30)   NOT NULL,
    policy_value                         INTEGER      ,
    CONSTRAINT user_account_policy_pk PRIMARY KEY (id)
);

-- User accounts with authentication credentials
CREATE TABLE IF NOT EXISTS user_account (
    id                                   BIGINT        NOT NULL,
    first_name                           VARCHAR(80)   NOT NULL,
    last_name                            VARCHAR(80)   NOT NULL,
    user_name                            VARCHAR(80)   NOT NULL,
    user_email                           VARCHAR(255) ,
    phone                                VARCHAR(20)  ,
    locale                               VARCHAR(10)  ,
    status                               CHAR(1)       NOT NULL,
    passtext                             VARCHAR(128) ,
    passdate                             TIMESTAMP    ,
    login_attempts                       SMALLINT      NOT NULL DEFAULT 0,
    last_login_attempt                   TIMESTAMP    ,
    lock_time                            TIMESTAMP    ,
    twofa_enabled                        BOOLEAN       DEFAULT FALSE,
    twofa_method                         CHAR(1)      ,
    twofa_secret                         VARCHAR(128) ,
    twofa_backup_codes                   TEXT         ,
    twofa_enabled_at                     TIMESTAMP    ,
    deleted_at                           TIMESTAMP    ,
    single_device_session                BOOLEAN       NOT NULL DEFAULT FALSE,
    CONSTRAINT user_account_pk PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS user_account_email_uq ON user_account(user_email);
CREATE UNIQUE INDEX IF NOT EXISTS user_account_phone_uq ON user_account(phone);

-- User-to-role assignments
CREATE TABLE IF NOT EXISTS user_permission (
    user_id                              BIGINT        NOT NULL,
    role_id                              VARCHAR(30)   NOT NULL,
    begda                                TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    endda                                TIMESTAMP    ,
    CONSTRAINT user_permission_pk PRIMARY KEY (user_id, role_id, begda)
);
CREATE INDEX IF NOT EXISTS idx_user_permission_role ON user_permission(role_id);

-- Login audit trail
CREATE TABLE IF NOT EXISTS user_account_history (
    user_id                              BIGINT        NOT NULL,
    action_time                          TIMESTAMP     NOT NULL,
    action_type                          CHAR(1)       NOT NULL,
    status                               CHAR(1)       NOT NULL,
    object_name                          VARCHAR(80)  ,
    client_address                       VARCHAR(15)  ,
    CONSTRAINT user_account_history_pk PRIMARY KEY (user_id, action_time)
);

-- Pending user registrations, password reset tokens, and 2FA login tokens
CREATE TABLE IF NOT EXISTS user_registration (
    user_email                           VARCHAR(255)  NOT NULL,
    confirmation                         INTEGER       NOT NULL,
    payload                              TEXT         ,
    status                               CHAR(1)       NOT NULL DEFAULT 'P',
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_at                         TIMESTAMP    ,
    user_id                              BIGINT       ,
    attempts                             INTEGER       NOT NULL DEFAULT 0,
    CONSTRAINT user_registration_pk PRIMARY KEY (user_email, confirmation)
);

-- Multi-tenant business partner entity — shared core only (id + caption). Projects create separate tables for domain-specific extensions (e.g. partner_profile, partner_branding).
CREATE TABLE IF NOT EXISTS business_partner (
    id                                   BIGINT        NOT NULL,
    caption                              VARCHAR(200)  NOT NULL,
    CONSTRAINT business_partner_pk PRIMARY KEY (id)
);

CREATE SEQUENCE IF NOT EXISTS business_partner_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('business_partner', 'id', 'business_partner_seq') ON CONFLICT DO NOTHING;

-- Associates users with business partners
CREATE TABLE IF NOT EXISTS partner_user (
    partner_id                           BIGINT        NOT NULL,
    user_id                              BIGINT        NOT NULL,
    begda                                TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    endda                                TIMESTAMP    ,
    CONSTRAINT partner_user_pk PRIMARY KEY (partner_id, user_id, begda)
);
CREATE INDEX IF NOT EXISTS idx_partner_user_user ON partner_user(user_id);

-- Business partner addresses
CREATE TABLE IF NOT EXISTS partner_address (
    partner_id                           BIGINT        NOT NULL,
    address                              VARCHAR(200)  NOT NULL,
    city                                 VARCHAR(80)  ,
    country                              CHAR(2)      ,
    state                                CHAR(2)      ,
    zipcode                              VARCHAR(10)  ,
    phone                                VARCHAR(20)  ,
    latitude                             NUMERIC(10,7),
    longitude                            NUMERIC(10,7),
    CONSTRAINT partner_address_pk PRIMARY KEY (partner_id, address)
);

-- Partner website domains
CREATE TABLE IF NOT EXISTS partner_domain (
    partner_id                           BIGINT        NOT NULL,
    domain_url                           VARCHAR(255)  NOT NULL,
    is_primary                           BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT partner_domain_pk PRIMARY KEY (partner_id, domain_url)
);

-- Per-column UI/CRUD display overrides (mode, field width, textarea rows)
CREATE TABLE IF NOT EXISTS column_display_attribute (
    table_name                           VARCHAR(63)   NOT NULL,
    column_name                          VARCHAR(63)   NOT NULL,
    display_mode                         CHAR(1)      ,
    display_width                        INTEGER      ,
    display_rows                         INTEGER      ,
    CONSTRAINT column_display_attribute_pk PRIMARY KEY (table_name, column_name)
);

-- JWT refresh tokens
CREATE TABLE IF NOT EXISTS user_refresh_token (
    id                                   BIGINT        NOT NULL,
    user_id                              BIGINT        NOT NULL,
    token_hash                           VARCHAR(128)  NOT NULL,
    expires_at                           TIMESTAMP     NOT NULL,
    revoked_at                           TIMESTAMP    ,
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_refresh_token_pk PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_refresh_token_hash ON user_refresh_token(token_hash);

CREATE SEQUENCE IF NOT EXISTS user_refresh_token_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('user_refresh_token', 'id', 'user_refresh_token_seq') ON CONFLICT DO NOTHING;

-- Trusted devices for 2FA bypass; device_fingerprint holds hex SHA256 of a server-minted secret kept in an HttpOnly cookie (never the raw secret).
CREATE TABLE IF NOT EXISTS user_trusted_device (
    id                                   BIGINT        NOT NULL,
    user_id                              BIGINT        NOT NULL,
    device_fingerprint                   VARCHAR(128)  NOT NULL,
    device_name                          VARCHAR(200) ,
    trusted_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at                           TIMESTAMP     NOT NULL,
    last_seen_at                         TIMESTAMP    ,
    CONSTRAINT user_trusted_device_pk PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_trusted_device_user ON user_trusted_device(user_id, device_fingerprint);

CREATE SEQUENCE IF NOT EXISTS user_trusted_device_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('user_trusted_device', 'id', 'user_trusted_device_seq') ON CONFLICT DO NOTHING;

-- API keys for public API access with rotation support
CREATE TABLE IF NOT EXISTS api_key (
    id                                   BIGINT        NOT NULL,
    partner_id                           BIGINT        NOT NULL,
    key_name                             VARCHAR(100)  NOT NULL,
    key_prefix                           CHAR(8)       NOT NULL,
    key_hash                             CHAR(64)      NOT NULL,
    scopes                               VARCHAR(500)  NOT NULL DEFAULT 'query',
    is_active                            BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at                           TIMESTAMP    ,
    last_used_at                         TIMESTAMP    ,
    user_id                              BIGINT       ,
    rotated_at                           TIMESTAMP    ,
    grace_expires_at                     TIMESTAMP    ,
    CONSTRAINT api_key_pk PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_api_key_hash ON api_key(key_hash);
CREATE INDEX IF NOT EXISTS idx_api_key_partner ON api_key(partner_id);

CREATE SEQUENCE IF NOT EXISTS api_key_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('api_key', 'id', 'api_key_seq') ON CONFLICT DO NOTHING;

-- One-time password codes for phone/email verification
CREATE TABLE IF NOT EXISTS user_otp (
    id                                   BIGINT        NOT NULL,
    user_id                              BIGINT        NOT NULL,
    code                                 VARCHAR(6)    NOT NULL,
    purpose                              VARCHAR(20)   NOT NULL,
    expires_at                           TIMESTAMP     NOT NULL,
    attempts                             INTEGER       NOT NULL DEFAULT 0,
    CONSTRAINT user_otp_pk PRIMARY KEY (id)
);

CREATE SEQUENCE IF NOT EXISTS user_otp_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('user_otp', 'id', 'user_otp_seq') ON CONFLICT DO NOTHING;

-- Social login provider links (Google, Apple)
CREATE TABLE IF NOT EXISTS user_social_provider (
    user_id                              BIGINT        NOT NULL,
    provider                             VARCHAR(20)   NOT NULL,
    provider_id                          VARCHAR(255)  NOT NULL,
    CONSTRAINT user_social_provider_pk PRIMARY KEY (user_id, provider)
);

-- Versioned privacy/terms/consent policy text registered for audit trail
CREATE TABLE IF NOT EXISTS consent_policy (
    id                                   BIGINT        NOT NULL,
    policy_type                          VARCHAR(30)   NOT NULL,
    region                               VARCHAR(10)   NOT NULL DEFAULT 'global',
    version                              VARCHAR(64)   NOT NULL,
    language                             VARCHAR(8)    NOT NULL DEFAULT 'en',
    content_url                          VARCHAR(500)  NOT NULL,
    content_sha256                       VARCHAR(64)   NOT NULL,
    effective_from                       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deprecated_at                        TIMESTAMP    ,
    CONSTRAINT consent_policy_pk PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS consent_policy_uq ON consent_policy(policy_type, region, version, language);

CREATE SEQUENCE IF NOT EXISTS consent_policy_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('consent_policy', 'id', 'consent_policy_seq') ON CONFLICT DO NOTHING;

-- Per-user consent decisions with full audit trail for PIPEDA/GDPR
CREATE TABLE IF NOT EXISTS consent_event (
    id                                   BIGINT        NOT NULL,
    user_id                              BIGINT       ,
    email_hash                           VARCHAR(64)  ,
    consent_type                         VARCHAR(30)   NOT NULL,
    consented                            BOOLEAN       NOT NULL,
    policy_id                            BIGINT        NOT NULL,
    event_ref                            VARCHAR(64)  ,
    region                               VARCHAR(10)   NOT NULL,
    client_ip                            VARCHAR(45)  ,
    client_user_agent                    VARCHAR(500) ,
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT consent_event_pk PRIMARY KEY (id),
    CONSTRAINT consent_event_identity CHECK (user_id IS NOT NULL OR email_hash IS NOT NULL)
);
CREATE INDEX IF NOT EXISTS idx_consent_event_user ON consent_event(user_id, consent_type);
CREATE INDEX IF NOT EXISTS idx_consent_event_email ON consent_event(email_hash, consent_type);

CREATE SEQUENCE IF NOT EXISTS consent_event_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('consent_event', 'id', 'consent_event_seq') ON CONFLICT DO NOTHING;

-- Mobile device push-notification tokens (FCM / APNs via FCM)
CREATE TABLE IF NOT EXISTS device_token (
    id                                   BIGINT        NOT NULL,
    user_id                              BIGINT        NOT NULL,
    platform                             CHAR(1)       NOT NULL,
    token                                TEXT          NOT NULL,
    app_version                          VARCHAR(32)  ,
    device_model                         VARCHAR(64)  ,
    is_active                            BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at                         TIMESTAMP    ,
    CONSTRAINT device_token_pk PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS device_token_user_token_uq ON device_token(user_id, token);
CREATE INDEX IF NOT EXISTS idx_device_token_user_active ON device_token(user_id, is_active);

CREATE SEQUENCE IF NOT EXISTS device_token_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('device_token', 'id', 'device_token_seq') ON CONFLICT DO NOTHING;

-- Subscription plans with pricing
CREATE TABLE IF NOT EXISTS subscription_plan (
    id                                   VARCHAR(20)   NOT NULL,
    caption                              VARCHAR(80)   NOT NULL,
    is_active                            BOOLEAN       NOT NULL DEFAULT TRUE,
    monthly_cost                         NUMERIC(18,2) NOT NULL,
    annual_cost                          NUMERIC(18,2) NOT NULL,
    currency                             CHAR(3)       NOT NULL DEFAULT 'USD',
    provider_price_id                    VARCHAR(64)  ,
    activation_mode                      CHAR(1)       NOT NULL DEFAULT 'A',
    trial_days                           INTEGER      ,
    CONSTRAINT subscription_plan_pk PRIMARY KEY (id)
);

-- Quota-tracked resources (domains, API calls, etc.)
CREATE TABLE IF NOT EXISTS subscription_resource (
    id                                   VARCHAR(20)   NOT NULL,
    table_name                           VARCHAR(32)  ,
    status_column                        VARCHAR(32)  ,
    status_value                         VARCHAR(80)  ,
    date_column                          VARCHAR(32)  ,
    CONSTRAINT subscription_resource_pk PRIMARY KEY (id)
);

-- Resource limits per subscription plan
CREATE TABLE IF NOT EXISTS subscription_quota (
    plan_id                              VARCHAR(20)   NOT NULL,
    resource_id                          VARCHAR(20)   NOT NULL,
    max_value                            BIGINT        NOT NULL,
    period_type                          CHAR(1)       NOT NULL DEFAULT 'M',
    CONSTRAINT subscription_quota_pk PRIMARY KEY (plan_id, resource_id)
);

-- Optional add-on features with separate pricing
CREATE TABLE IF NOT EXISTS subscription_addon (
    id                                   VARCHAR(20)   NOT NULL,
    caption                              VARCHAR(80)   NOT NULL,
    max_value                            BIGINT        NOT NULL,
    is_active                            BOOLEAN       NOT NULL DEFAULT TRUE,
    monthly_cost                         NUMERIC(18,2) NOT NULL,
    currency                             CHAR(3)       NOT NULL DEFAULT 'USD',
    period_type                          CHAR(1)       NOT NULL DEFAULT 'M',
    description                          VARCHAR(255) ,
    CONSTRAINT subscription_addon_pk PRIMARY KEY (id)
);

-- Active plan subscriptions per business partner
CREATE TABLE IF NOT EXISTS partner_plan_subscription (
    partner_id                           BIGINT        NOT NULL,
    plan_id                              VARCHAR(20)   NOT NULL,
    begda                                TIMESTAMP     NOT NULL,
    endda                                TIMESTAMP    ,
    monthly_cost                         NUMERIC(18,2) NOT NULL,
    currency                             CHAR(3)       NOT NULL,
    status                               CHAR(1)       NOT NULL,
    auto_renew                           BOOLEAN       NOT NULL DEFAULT TRUE,
    provider_subscription_id             VARCHAR(64)  ,
    billing_cycle                        CHAR(1)      ,
    renewal_date                         TIMESTAMP    ,
    cancelled_at                         TIMESTAMP    ,
    effective_cancel_date                TIMESTAMP    ,
    trial_end                            TIMESTAMP    ,
    seats                                INTEGER      ,
    CONSTRAINT partner_plan_subscription_pk PRIMARY KEY (partner_id, plan_id, begda)
);
CREATE INDEX IF NOT EXISTS idx_partner_plan_subscription_provider_sub ON partner_plan_subscription(provider_subscription_id);

-- Active add-on subscriptions per business partner
CREATE TABLE IF NOT EXISTS partner_addon_subscription (
    partner_id                           BIGINT        NOT NULL,
    addon_id                             VARCHAR(20)   NOT NULL,
    auto_increase                        BOOLEAN       NOT NULL DEFAULT FALSE,
    begda                                TIMESTAMP     NOT NULL,
    endda                                TIMESTAMP    ,
    monthly_cost                         NUMERIC(18,2) NOT NULL,
    currency                             CHAR(3)       NOT NULL,
    status                               CHAR(1)       NOT NULL,
    auto_renew                           BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT partner_addon_subscription_pk PRIMARY KEY (partner_id, addon_id, begda)
);

-- Resource usage tracking for quota enforcement
CREATE TABLE IF NOT EXISTS usage_ledger (
    partner_id                           BIGINT        NOT NULL,
    usage_time                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resource_name                        VARCHAR(50)   NOT NULL,
    amount                               BIGINT        NOT NULL,
    notes                                VARCHAR(255) ,
    CONSTRAINT usage_ledger_pk PRIMARY KEY (partner_id, usage_time)
);

-- Raw inbound payment provider webhooks — idempotency + audit
CREATE TABLE IF NOT EXISTS payment_webhook_log (
    id                                   BIGINT        NOT NULL,
    provider                             VARCHAR(30)   NOT NULL,
    event_id                             VARCHAR(255)  NOT NULL,
    event_type                           VARCHAR(100)  NOT NULL,
    processing_status                    CHAR(1)       NOT NULL DEFAULT 'R',
    error_message                        TEXT         ,
    raw_payload                          TEXT         ,
    received_at                          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at                         TIMESTAMP    ,
    CONSTRAINT payment_webhook_log_pk PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS payment_webhook_log_uq ON payment_webhook_log(provider, event_id);

CREATE SEQUENCE IF NOT EXISTS payment_webhook_log_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('payment_webhook_log', 'id', 'payment_webhook_log_seq') ON CONFLICT DO NOTHING;

-- Stored payment methods per business partner (provider customer tokens)
CREATE TABLE IF NOT EXISTS payment_method (
    id                                   BIGINT        NOT NULL,
    partner_id                           BIGINT        NOT NULL,
    provider                             VARCHAR(30)   NOT NULL,
    provider_token                       VARCHAR(255)  NOT NULL,
    method_type                          VARCHAR(20)   NOT NULL,
    is_default                           BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payment_method_pk PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_payment_method_default ON payment_method(partner_id, is_default);

CREATE SEQUENCE IF NOT EXISTS payment_method_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('payment_method', 'id', 'payment_method_seq') ON CONFLICT DO NOTHING;

-- Completed/failed/refunded payment transactions per partner
CREATE TABLE IF NOT EXISTS payment_record (
    id                                   BIGINT        NOT NULL,
    partner_id                           BIGINT       ,
    provider                             VARCHAR(30)   NOT NULL,
    provider_payment_id                  VARCHAR(255) ,
    provider_event_type                  VARCHAR(100) ,
    amount                               NUMERIC(18,2) NOT NULL,
    currency                             CHAR(3)       NOT NULL,
    plan_id                              VARCHAR(20)  ,
    invoice_id                           BIGINT       ,
    payment_status                       CHAR(1)       NOT NULL,
    paid_at                              TIMESTAMP    ,
    raw_payload                          TEXT         ,
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payment_record_pk PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_payment_record_partner ON payment_record(partner_id, paid_at);

CREATE SEQUENCE IF NOT EXISTS payment_record_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('payment_record', 'id', 'payment_record_seq') ON CONFLICT DO NOTHING;

-- Per (user, partner) bank account details for out-bound payouts.
-- Owned by keel/payout. Raw routing details live with the provider
-- (Airwallex / Stripe Connect / Wise); this row carries only the
-- provider handle plus tax/correspondence metadata.
CREATE TABLE IF NOT EXISTS user_bank_info (
    user_id                              BIGINT        NOT NULL,
    partner_id                           BIGINT        NOT NULL,
    country_code                         CHAR(2)       NOT NULL,
    currency                             CHAR(3)       NOT NULL,
    account_holder_name                  VARCHAR(200)  NOT NULL,
    billing_address                      TEXT          NOT NULL,
    tax_id_type                          CHAR(1)       NOT NULL,
    tax_id_encrypted                     BYTEA         NOT NULL,
    provider                             CHAR(2)       NOT NULL,
    provider_account_id                  VARCHAR(100) ,
    provider_agreement                   BOOLEAN       NOT NULL DEFAULT FALSE,
    provider_onboarded_at                TIMESTAMP    ,
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_bank_info_pk PRIMARY KEY (user_id, partner_id)
);
CREATE INDEX IF NOT EXISTS idx_user_bank_info_partner ON user_bank_info(partner_id);

-- Saved payment methods for end users (cards, wallets, bank accounts).
-- Distinct from `payment_method`, which is partner-scoped for SaaS
-- billing — this row is per (user_id), the consumer cards a user has
-- on file for in-bound payments. provider_token is the provider's
-- reusable handle (Stripe PaymentMethod id, SetupIntent id, etc.);
-- raw card numbers / IBANs / SWIFT never land here.
CREATE TABLE IF NOT EXISTS user_payment_method (
    id                                   BIGINT        NOT NULL,
    user_id                              BIGINT        NOT NULL,
    method_type                          VARCHAR(20)   NOT NULL,
    provider                             VARCHAR(30)   NOT NULL,
    provider_token                       VARCHAR(255)  NOT NULL,
    last_four                            VARCHAR(4)   ,
    brand                                VARCHAR(20)  ,
    expiry_month                         SMALLINT     ,
    expiry_year                          SMALLINT     ,
    currency                             CHAR(3)       NOT NULL DEFAULT 'USD',
    is_default                           BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_payment_method_pk PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_user_payment_method_user ON user_payment_method(user_id, is_default);

CREATE SEQUENCE IF NOT EXISTS user_payment_method_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('user_payment_method', 'id', 'user_payment_method_seq') ON CONFLICT DO NOTHING;

-- Per-table custom actions surfaced as buttons in CRUD UIs. Each row
-- registers ONE action; the downstream application must also (a) seed
-- the matching authorization_object + authorization_object_action rows
-- so roles can grant access, and (b) register an HTTP handler at the
-- conventional URL POST /<rest_prefix>/<table_name>/<action_name>.
-- 
-- authorization_object.id mirrors the uppercased table name and
-- authorization_object_action.action mirrors the uppercased action_name
-- — gives each table its own action namespace so the same action name
-- ('assign', 'enable', 'calculate') can mean different things on
-- different tables without a shared auth dimension.
-- 
-- record_specific=TRUE  → button renders next to per-row edit/delete.
-- record_specific=FALSE → button renders next to the "New Record"
--                         control at the table-level toolbar.
-- 
-- Reserved action_name values that collide with generic CRUD subpaths
-- (list / get / post / delete / get-paginated) are rejected at REST
-- service boot.
CREATE TABLE IF NOT EXISTS table_action (
    table_name                           VARCHAR(80)   NOT NULL,
    action_name                          VARCHAR(30)   NOT NULL,
    caption                              VARCHAR(80)   NOT NULL,
    icon                                 VARCHAR(40)  ,
    record_specific                      BOOLEAN       NOT NULL DEFAULT FALSE,
    method_name                          VARCHAR(80)  ,
    display_order                        SMALLINT      NOT NULL DEFAULT 10,
    confirm_message                      VARCHAR(200) ,
    CONSTRAINT table_action_pk PRIMARY KEY (table_name, action_name)
);
CREATE INDEX IF NOT EXISTS idx_table_action_table ON table_action(table_name);

-- Billing invoices per partner (provider-issued or self-scheduled)
CREATE TABLE IF NOT EXISTS invoice (
    id                                   BIGINT        NOT NULL,
    partner_id                           BIGINT        NOT NULL,
    invoice_number                       VARCHAR(30)   NOT NULL,
    status                               CHAR(1)       NOT NULL DEFAULT 'D',
    subtotal                             NUMERIC(18,2) NOT NULL,
    tax                                  NUMERIC(18,2) NOT NULL DEFAULT 0.00,
    total                                NUMERIC(18,2) NOT NULL,
    total_minor                          BIGINT        NOT NULL DEFAULT 0,
    currency                             CHAR(3)       NOT NULL DEFAULT 'USD',
    issued_at                            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    due_at                               TIMESTAMP    ,
    paid_at                              TIMESTAMP    ,
    pdf_storage_path                     VARCHAR(500) ,
    provider_invoice_id                  VARCHAR(255) ,
    provider_charge_id                   VARCHAR(255) ,
    attempt_count                        INTEGER       NOT NULL DEFAULT 0,
    next_attempt_at                      TIMESTAMP    ,
    last_error                           TEXT         ,
    CONSTRAINT invoice_pk PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_invoice_number ON invoice(invoice_number);
CREATE INDEX IF NOT EXISTS idx_invoice_partner ON invoice(partner_id);

CREATE SEQUENCE IF NOT EXISTS invoice_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('invoice', 'id', 'invoice_seq') ON CONFLICT DO NOTHING;

-- Line items for an invoice
CREATE TABLE IF NOT EXISTS invoice_line (
    invoice_id                           BIGINT        NOT NULL,
    seq                                  INTEGER       NOT NULL,
    description                          VARCHAR(200)  NOT NULL,
    quantity                             INTEGER       NOT NULL DEFAULT 1,
    unit_price                           NUMERIC(18,2) NOT NULL,
    amount                               NUMERIC(18,2) NOT NULL,
    CONSTRAINT invoice_line_pk PRIMARY KEY (invoice_id, seq)
);

-- Partner ↔ provider-customer token (one per partner+provider)
CREATE TABLE IF NOT EXISTS partner_billing_customer (
    partner_id                           BIGINT        NOT NULL,
    provider                             VARCHAR(30)   NOT NULL,
    customer_token                       VARCHAR(255)  NOT NULL,
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT partner_billing_customer_pk PRIMARY KEY (partner_id, provider)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_partner_billing_customer_token ON partner_billing_customer(provider, customer_token);

-- Foreign keys (emitted post-CREATE so order doesn't matter)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'constant_values' AND table_name = 'constant_value'
  ) THEN
    ALTER TABLE constant_value ADD CONSTRAINT constant_values FOREIGN KEY (constant_id) REFERENCES constant_header(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'constant_lookups' AND table_name = 'constant_lookup'
  ) THEN
    ALTER TABLE constant_lookup ADD CONSTRAINT constant_lookups FOREIGN KEY (constant_id) REFERENCES constant_header(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'rest_api_children' AND table_name = 'rest_api_child'
  ) THEN
    ALTER TABLE rest_api_child ADD CONSTRAINT rest_api_children FOREIGN KEY (api_id) REFERENCES rest_api_header(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'rest_api_lookups' AND table_name = 'rest_api_child'
  ) THEN
    ALTER TABLE rest_api_child ADD CONSTRAINT rest_api_lookups FOREIGN KEY (constraint_name) REFERENCES foreign_key_lookup(constraint_name);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'rest_report_params' AND table_name = 'rest_report_param'
  ) THEN
    ALTER TABLE rest_report_param ADD CONSTRAINT rest_report_params FOREIGN KEY (report_id) REFERENCES rest_report_header(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'rest_report_param_constants' AND table_name = 'rest_report_param'
  ) THEN
    ALTER TABLE rest_report_param ADD CONSTRAINT rest_report_param_constants FOREIGN KEY (constant_id) REFERENCES constant_header(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'application_menu_items' AND table_name = 'application_menu_item'
  ) THEN
    ALTER TABLE application_menu_item ADD CONSTRAINT application_menu_items FOREIGN KEY (menu_id) REFERENCES application_menu(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'authorization_object_actions' AND table_name = 'authorization_object_action'
  ) THEN
    ALTER TABLE authorization_object_action ADD CONSTRAINT authorization_object_actions FOREIGN KEY (authorization_object_id) REFERENCES authorization_object(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'states' AND table_name = 'state'
  ) THEN
    ALTER TABLE state ADD CONSTRAINT states FOREIGN KEY (country_id) REFERENCES country(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'counties' AND table_name = 'county'
  ) THEN
    ALTER TABLE county ADD CONSTRAINT counties FOREIGN KEY (country_id, state_id) REFERENCES state(country_id, id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'authorization_role_permissions' AND table_name = 'authorization_role_permission'
  ) THEN
    ALTER TABLE authorization_role_permission ADD CONSTRAINT authorization_role_permissions FOREIGN KEY (role_id) REFERENCES authorization_role(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'permitted_object_action' AND table_name = 'authorization_role_permission'
  ) THEN
    ALTER TABLE authorization_role_permission ADD CONSTRAINT permitted_object_action FOREIGN KEY (authorization_object_id, action) REFERENCES authorization_object_action(authorization_object_id, action);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'user_permissions' AND table_name = 'user_permission'
  ) THEN
    ALTER TABLE user_permission ADD CONSTRAINT user_permissions FOREIGN KEY (user_id) REFERENCES user_account(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'permitted_users' AND table_name = 'user_permission'
  ) THEN
    ALTER TABLE user_permission ADD CONSTRAINT permitted_users FOREIGN KEY (role_id) REFERENCES authorization_role(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'user_historic_actions' AND table_name = 'user_account_history'
  ) THEN
    ALTER TABLE user_account_history ADD CONSTRAINT user_historic_actions FOREIGN KEY (user_id) REFERENCES user_account(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'partner_users' AND table_name = 'partner_user'
  ) THEN
    ALTER TABLE partner_user ADD CONSTRAINT partner_users FOREIGN KEY (partner_id) REFERENCES business_partner(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'user_partners' AND table_name = 'partner_user'
  ) THEN
    ALTER TABLE partner_user ADD CONSTRAINT user_partners FOREIGN KEY (user_id) REFERENCES user_account(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'partner_addresses' AND table_name = 'partner_address'
  ) THEN
    ALTER TABLE partner_address ADD CONSTRAINT partner_addresses FOREIGN KEY (partner_id) REFERENCES business_partner(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'partner_address_countries' AND table_name = 'partner_address'
  ) THEN
    ALTER TABLE partner_address ADD CONSTRAINT partner_address_countries FOREIGN KEY (country) REFERENCES country(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'partner_address_states' AND table_name = 'partner_address'
  ) THEN
    ALTER TABLE partner_address ADD CONSTRAINT partner_address_states FOREIGN KEY (country, state) REFERENCES state(country_id, id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'partner_domains' AND table_name = 'partner_domain'
  ) THEN
    ALTER TABLE partner_domain ADD CONSTRAINT partner_domains FOREIGN KEY (partner_id) REFERENCES business_partner(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'user_refresh_tokens' AND table_name = 'user_refresh_token'
  ) THEN
    ALTER TABLE user_refresh_token ADD CONSTRAINT user_refresh_tokens FOREIGN KEY (user_id) REFERENCES user_account(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'user_trusted_devices' AND table_name = 'user_trusted_device'
  ) THEN
    ALTER TABLE user_trusted_device ADD CONSTRAINT user_trusted_devices FOREIGN KEY (user_id) REFERENCES user_account(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'api_key_partners' AND table_name = 'api_key'
  ) THEN
    ALTER TABLE api_key ADD CONSTRAINT api_key_partners FOREIGN KEY (partner_id) REFERENCES business_partner(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'api_key_users' AND table_name = 'api_key'
  ) THEN
    ALTER TABLE api_key ADD CONSTRAINT api_key_users FOREIGN KEY (user_id) REFERENCES user_account(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'user_otps' AND table_name = 'user_otp'
  ) THEN
    ALTER TABLE user_otp ADD CONSTRAINT user_otps FOREIGN KEY (user_id) REFERENCES user_account(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'user_social_providers' AND table_name = 'user_social_provider'
  ) THEN
    ALTER TABLE user_social_provider ADD CONSTRAINT user_social_providers FOREIGN KEY (user_id) REFERENCES user_account(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'consent_event_policies' AND table_name = 'consent_event'
  ) THEN
    ALTER TABLE consent_event ADD CONSTRAINT consent_event_policies FOREIGN KEY (policy_id) REFERENCES consent_policy(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'consent_event_users' AND table_name = 'consent_event'
  ) THEN
    ALTER TABLE consent_event ADD CONSTRAINT consent_event_users FOREIGN KEY (user_id) REFERENCES user_account(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'device_token_users' AND table_name = 'device_token'
  ) THEN
    ALTER TABLE device_token ADD CONSTRAINT device_token_users FOREIGN KEY (user_id) REFERENCES user_account(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'subscription_quotas' AND table_name = 'subscription_quota'
  ) THEN
    ALTER TABLE subscription_quota ADD CONSTRAINT subscription_quotas FOREIGN KEY (plan_id) REFERENCES subscription_plan(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'sub_resources_quotas' AND table_name = 'subscription_quota'
  ) THEN
    ALTER TABLE subscription_quota ADD CONSTRAINT sub_resources_quotas FOREIGN KEY (resource_id) REFERENCES subscription_resource(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'partner_plan_subscriptions' AND table_name = 'partner_plan_subscription'
  ) THEN
    ALTER TABLE partner_plan_subscription ADD CONSTRAINT partner_plan_subscriptions FOREIGN KEY (partner_id) REFERENCES business_partner(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'partner_subscriptions_plan' AND table_name = 'partner_plan_subscription'
  ) THEN
    ALTER TABLE partner_plan_subscription ADD CONSTRAINT partner_subscriptions_plan FOREIGN KEY (plan_id) REFERENCES subscription_plan(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'partner_addon_subscriptions' AND table_name = 'partner_addon_subscription'
  ) THEN
    ALTER TABLE partner_addon_subscription ADD CONSTRAINT partner_addon_subscriptions FOREIGN KEY (partner_id) REFERENCES business_partner(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'partner_subscriptions_addon' AND table_name = 'partner_addon_subscription'
  ) THEN
    ALTER TABLE partner_addon_subscription ADD CONSTRAINT partner_subscriptions_addon FOREIGN KEY (addon_id) REFERENCES subscription_addon(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'partner_usage_ledger' AND table_name = 'usage_ledger'
  ) THEN
    ALTER TABLE usage_ledger ADD CONSTRAINT partner_usage_ledger FOREIGN KEY (partner_id) REFERENCES business_partner(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'partner_payment_methods' AND table_name = 'payment_method'
  ) THEN
    ALTER TABLE payment_method ADD CONSTRAINT partner_payment_methods FOREIGN KEY (partner_id) REFERENCES business_partner(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'partner_payment_records' AND table_name = 'payment_record'
  ) THEN
    ALTER TABLE payment_record ADD CONSTRAINT partner_payment_records FOREIGN KEY (partner_id) REFERENCES business_partner(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'payment_record_plans' AND table_name = 'payment_record'
  ) THEN
    ALTER TABLE payment_record ADD CONSTRAINT payment_record_plans FOREIGN KEY (plan_id) REFERENCES subscription_plan(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'user_bank_info_users' AND table_name = 'user_bank_info'
  ) THEN
    ALTER TABLE user_bank_info ADD CONSTRAINT user_bank_info_users FOREIGN KEY (user_id) REFERENCES user_account(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'user_bank_info_partners' AND table_name = 'user_bank_info'
  ) THEN
    ALTER TABLE user_bank_info ADD CONSTRAINT user_bank_info_partners FOREIGN KEY (partner_id) REFERENCES business_partner(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'user_payment_method_users' AND table_name = 'user_payment_method'
  ) THEN
    ALTER TABLE user_payment_method ADD CONSTRAINT user_payment_method_users FOREIGN KEY (user_id) REFERENCES user_account(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'partner_invoices' AND table_name = 'invoice'
  ) THEN
    ALTER TABLE invoice ADD CONSTRAINT partner_invoices FOREIGN KEY (partner_id) REFERENCES business_partner(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'invoice_lines' AND table_name = 'invoice_line'
  ) THEN
    ALTER TABLE invoice_line ADD CONSTRAINT invoice_lines FOREIGN KEY (invoice_id) REFERENCES invoice(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'partner_billing_customers' AND table_name = 'partner_billing_customer'
  ) THEN
    ALTER TABLE partner_billing_customer ADD CONSTRAINT partner_billing_customers FOREIGN KEY (partner_id) REFERENCES business_partner(id);
  END IF;
END $$;
