-- ==========================================================================
-- Generated by schemagen — do not edit manually
-- ==========================================================================

-- Dropdown/enum header definitions
CREATE TABLE IF NOT EXISTS constant_header (
    id                                   VARCHAR(60)   NOT NULL,
    caption                              VARCHAR(80)   NOT NULL,
    CONSTRAINT constant_header_pk PRIMARY KEY (id)
);

-- Dropdown/enum values for each constant header
CREATE TABLE IF NOT EXISTS constant_value (
    constant_id                          VARCHAR(60)   NOT NULL,
    value                                VARCHAR(80)   NOT NULL,
    caption                              VARCHAR(80)   NOT NULL,
    CONSTRAINT constant_value_pk PRIMARY KEY (constant_id, value)
);

-- Maps constant domains to table columns
CREATE TABLE IF NOT EXISTS constant_lookup (
    constant_id                          VARCHAR(60)   NOT NULL,
    table_name                           VARCHAR(60)   NOT NULL,
    column_name                          VARCHAR(60)   NOT NULL,
    CONSTRAINT constant_lookup_pk PRIMARY KEY (constant_id, table_name, column_name)
);

-- Controls FK display behavior in the UI
CREATE TABLE IF NOT EXISTS foreign_key_lookup (
    constraint_name                      VARCHAR(60)   NOT NULL,
    lookup_style                         CHAR(1)       NOT NULL,
    display_column                       VARCHAR(60)   NOT NULL,
    CONSTRAINT foreign_key_lookup_pk PRIMARY KEY (constraint_name)
);

-- Metadata-driven REST API definitions
CREATE TABLE IF NOT EXISTS rest_api_header (
    id                                   VARCHAR(80)   NOT NULL,
    version                              VARCHAR(20)   NOT NULL DEFAULT 'v1',
    master_table                         VARCHAR(60)   NOT NULL,
    is_active                            BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT rest_api_header_pk PRIMARY KEY (id)
);

-- Child relations for REST APIs
CREATE TABLE IF NOT EXISTS rest_api_child (
    api_id                               VARCHAR(80)   NOT NULL,
    seq                                  INTEGER       NOT NULL,
    parent_seq                           INTEGER       NOT NULL DEFAULT 0,
    constraint_name                      VARCHAR(60)   NOT NULL,
    CONSTRAINT rest_api_child_pk PRIMARY KEY (api_id, seq)
);
CREATE INDEX IF NOT EXISTS idx_rest_api_child_fk ON rest_api_child(constraint_name);

-- Report definitions
CREATE TABLE IF NOT EXISTS rest_report_header (
    id                                   VARCHAR(80)   NOT NULL,
    version                              VARCHAR(20)   NOT NULL DEFAULT 'v1',
    query_name                           VARCHAR(60)   NOT NULL,
    description                          TEXT          NOT NULL,
    is_active                            BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT rest_report_header_pk PRIMARY KEY (id)
);

-- Report parameter definitions
CREATE TABLE IF NOT EXISTS rest_report_param (
    report_id                            VARCHAR(80)   NOT NULL,
    seq                                  INTEGER       NOT NULL,
    param_name                           VARCHAR(20)   NOT NULL,
    data_type                            VARCHAR(20)   NOT NULL DEFAULT 'string',
    constant_id                          VARCHAR(60)  ,
    CONSTRAINT rest_report_param_pk PRIMARY KEY (report_id, seq)
);

-- Maps tables to their PostgreSQL sequences
CREATE TABLE IF NOT EXISTS table_sequence_usage (
    table_name                           VARCHAR(32)   NOT NULL,
    column_name                          VARCHAR(32)   NOT NULL,
    sequence_name                        VARCHAR(32)   NOT NULL,
    CONSTRAINT table_sequence_usage_pk PRIMARY KEY (table_name)
);

-- Navigation menu structure
CREATE TABLE IF NOT EXISTS application_menu (
    id                                   VARCHAR(30)   NOT NULL,
    caption                              VARCHAR(80)   NOT NULL,
    display_order                        INTEGER       NOT NULL,
    is_active                            BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT application_menu_pk PRIMARY KEY (id)
);

-- Menu items with REST API links
CREATE TABLE IF NOT EXISTS application_menu_item (
    menu_id                              VARCHAR(30)   NOT NULL,
    item_id                              VARCHAR(30)   NOT NULL,
    caption                              TEXT          NOT NULL,
    display_order                        INTEGER       NOT NULL,
    rest_uri                             VARCHAR(255)  NOT NULL,
    is_active                            BOOLEAN       NOT NULL DEFAULT TRUE,
    filter_on_list                       BOOLEAN       NOT NULL DEFAULT FALSE,
    CONSTRAINT application_menu_item_pk PRIMARY KEY (menu_id, item_id)
);

-- RBAC authorization object definitions
CREATE TABLE IF NOT EXISTS authorization_object (
    id                                   VARCHAR(30)   NOT NULL,
    caption                              VARCHAR(80)   NOT NULL,
    CONSTRAINT authorization_object_pk PRIMARY KEY (id)
);

-- Actions available on each authorization object
CREATE TABLE IF NOT EXISTS authorization_object_action (
    authorization_object_id              VARCHAR(30)   NOT NULL,
    action                               VARCHAR(30)   NOT NULL,
    caption                              VARCHAR(80)   NOT NULL,
    CONSTRAINT authorization_object_action_pk PRIMARY KEY (authorization_object_id, action)
);

-- Background worker registration and heartbeat
CREATE TABLE IF NOT EXISTS service_registry (
    service_name                         VARCHAR(16)   NOT NULL,
    started_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    hostname                             VARCHAR(64)   NOT NULL,
    pid                                  BIGINT        NOT NULL,
    status                               CHAR(1)       NOT NULL,
    last_heartbeat                       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT service_registry_pk PRIMARY KEY (service_name, started_at)
);

-- Country reference table
CREATE TABLE IF NOT EXISTS country (
    id                                   CHAR(2)       NOT NULL,
    caption                              VARCHAR(100)  NOT NULL,
    currency                             CHAR(3)       NOT NULL,
    CONSTRAINT country_pk PRIMARY KEY (id)
);

-- State/province reference table
CREATE TABLE IF NOT EXISTS state (
    country_id                           CHAR(2)       NOT NULL,
    id                                   CHAR(2)       NOT NULL,
    caption                              VARCHAR(100)  NOT NULL,
    CONSTRAINT state_pk PRIMARY KEY (country_id, id)
);

-- County reference table
CREATE TABLE IF NOT EXISTS county (
    country_id                           CHAR(2)       NOT NULL,
    state_id                             CHAR(2)       NOT NULL,
    id                                   VARCHAR(100)  NOT NULL,
    CONSTRAINT county_pk PRIMARY KEY (country_id, state_id, id)
);

-- Authorization roles
CREATE TABLE IF NOT EXISTS authorization_role (
    id                                   VARCHAR(30)   NOT NULL,
    caption                              VARCHAR(80)   NOT NULL,
    CONSTRAINT authorization_role_pk PRIMARY KEY (id)
);

-- Role-based permission assignments
CREATE TABLE IF NOT EXISTS authorization_role_permission (
    role_id                              VARCHAR(30)   NOT NULL,
    authorization_object_id              VARCHAR(30)   NOT NULL,
    action                               VARCHAR(30)   NOT NULL,
    low_limit                            VARCHAR(80)   NOT NULL,
    high_limit                           VARCHAR(80)  ,
    bypass_scope                         BOOLEAN       NOT NULL DEFAULT FALSE,
    is_active                            BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT authorization_role_permission_pk PRIMARY KEY (role_id, authorization_object_id, action, low_limit)
);

-- Configurable password and login policies
CREATE TABLE IF NOT EXISTS user_account_policy (
    id                                   VARCHAR(30)   NOT NULL,
    policy_value                         INTEGER      ,
    CONSTRAINT user_account_policy_pk PRIMARY KEY (id)
);

-- User accounts with authentication credentials
CREATE TABLE IF NOT EXISTS user_account (
    id                                   BIGINT        NOT NULL,
    first_name                           VARCHAR(80)   NOT NULL,
    last_name                            VARCHAR(80)   NOT NULL,
    user_name                            VARCHAR(80)   NOT NULL,
    user_email                           VARCHAR(255) ,
    phone                                VARCHAR(20)  ,
    locale                               VARCHAR(10)  ,
    status                               CHAR(1)       NOT NULL,
    passtext                             VARCHAR(128) ,
    passdate                             TIMESTAMP    ,
    login_attempts                       SMALLINT      NOT NULL DEFAULT 0,
    last_login_attempt                   TIMESTAMP    ,
    lock_time                            TIMESTAMP    ,
    twofa_enabled                        BOOLEAN       DEFAULT FALSE,
    twofa_method                         CHAR(1)      ,
    twofa_secret                         VARCHAR(128) ,
    twofa_backup_codes                   TEXT         ,
    twofa_enabled_at                     TIMESTAMP    ,
    twofa_last_step                      BIGINT        NOT NULL DEFAULT 0,
    deleted_at                           TIMESTAMP    ,
    single_device_session                BOOLEAN       NOT NULL DEFAULT FALSE,
    CONSTRAINT user_account_pk PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS user_account_email_uq ON user_account(user_email);
CREATE UNIQUE INDEX IF NOT EXISTS user_account_phone_uq ON user_account(phone);

-- User-to-role assignments
CREATE TABLE IF NOT EXISTS user_permission (
    user_id                              BIGINT        NOT NULL,
    role_id                              VARCHAR(30)   NOT NULL,
    begda                                TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    endda                                TIMESTAMP    ,
    CONSTRAINT user_permission_pk PRIMARY KEY (user_id, role_id, begda)
);
CREATE INDEX IF NOT EXISTS idx_user_permission_role ON user_permission(role_id);

-- Login audit trail
CREATE TABLE IF NOT EXISTS user_account_history (
    user_id                              BIGINT        NOT NULL,
    action_time                          TIMESTAMP     NOT NULL,
    action_type                          CHAR(1)       NOT NULL,
    status                               CHAR(1)       NOT NULL,
    object_name                          VARCHAR(80)  ,
    client_address                       VARCHAR(15)  ,
    CONSTRAINT user_account_history_pk PRIMARY KEY (user_id, action_time)
);

-- Pending user registrations, password reset tokens, and 2FA login tokens
CREATE TABLE IF NOT EXISTS user_registration (
    user_email                           VARCHAR(255)  NOT NULL,
    confirmation                         INTEGER       NOT NULL,
    payload                              TEXT         ,
    status                               CHAR(1)       NOT NULL DEFAULT 'P',
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_at                         TIMESTAMP    ,
    user_id                              BIGINT       ,
    attempts                             INTEGER       NOT NULL DEFAULT 0,
    CONSTRAINT user_registration_pk PRIMARY KEY (user_email, confirmation)
);

-- Multi-tenant business partner entity — shared core only (id + caption). Projects create separate tables for domain-specific extensions (e.g. partner_profile, partner_branding).
CREATE TABLE IF NOT EXISTS business_partner (
    id                                   BIGINT        NOT NULL,
    caption                              VARCHAR(200)  NOT NULL,
    CONSTRAINT business_partner_pk PRIMARY KEY (id)
);

CREATE SEQUENCE IF NOT EXISTS business_partner_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('business_partner', 'id', 'business_partner_seq') ON CONFLICT DO NOTHING;

-- Associates users with business partners
CREATE TABLE IF NOT EXISTS partner_user (
    partner_id                           BIGINT        NOT NULL,
    user_id                              BIGINT        NOT NULL,
    begda                                TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    endda                                TIMESTAMP    ,
    CONSTRAINT partner_user_pk PRIMARY KEY (partner_id, user_id, begda)
);
CREATE INDEX IF NOT EXISTS idx_partner_user_user ON partner_user(user_id);

-- Business partner addresses
CREATE TABLE IF NOT EXISTS partner_address (
    partner_id                           BIGINT        NOT NULL,
    address                              VARCHAR(200)  NOT NULL,
    city                                 VARCHAR(80)  ,
    country                              CHAR(2)      ,
    state                                CHAR(2)      ,
    zipcode                              VARCHAR(10)  ,
    phone                                VARCHAR(20)  ,
    latitude                             NUMERIC(10,7),
    longitude                            NUMERIC(10,7),
    CONSTRAINT partner_address_pk PRIMARY KEY (partner_id, address)
);

-- Partner website domains
CREATE TABLE IF NOT EXISTS partner_domain (
    partner_id                           BIGINT        NOT NULL,
    domain_url                           VARCHAR(255)  NOT NULL,
    is_primary                           BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT partner_domain_pk PRIMARY KEY (partner_id, domain_url)
);

-- Per-column UI/CRUD display overrides (mode, field width, textarea rows)
CREATE TABLE IF NOT EXISTS column_display_attribute (
    table_name                           VARCHAR(63)   NOT NULL,
    column_name                          VARCHAR(63)   NOT NULL,
    display_mode                         CHAR(1)      ,
    display_width                        INTEGER      ,
    display_rows                         INTEGER      ,
    CONSTRAINT column_display_attribute_pk PRIMARY KEY (table_name, column_name)
);

-- JWT refresh tokens
CREATE TABLE IF NOT EXISTS user_refresh_token (
    id                                   BIGINT        NOT NULL,
    user_id                              BIGINT        NOT NULL,
    token_hash                           VARCHAR(128)  NOT NULL,
    expires_at                           TIMESTAMP     NOT NULL,
    revoked_at                           TIMESTAMP    ,
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_refresh_token_pk PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_refresh_token_hash ON user_refresh_token(token_hash);

CREATE SEQUENCE IF NOT EXISTS user_refresh_token_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('user_refresh_token', 'id', 'user_refresh_token_seq') ON CONFLICT DO NOTHING;

-- Trusted devices for 2FA bypass; device_fingerprint holds hex SHA256 of a server-minted secret kept in an HttpOnly cookie (never the raw secret).
CREATE TABLE IF NOT EXISTS user_trusted_device (
    id                                   BIGINT        NOT NULL,
    user_id                              BIGINT        NOT NULL,
    device_fingerprint                   VARCHAR(128)  NOT NULL,
    device_name                          VARCHAR(200) ,
    trusted_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at                           TIMESTAMP     NOT NULL,
    last_seen_at                         TIMESTAMP    ,
    CONSTRAINT user_trusted_device_pk PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_trusted_device_user ON user_trusted_device(user_id, device_fingerprint);

CREATE SEQUENCE IF NOT EXISTS user_trusted_device_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('user_trusted_device', 'id', 'user_trusted_device_seq') ON CONFLICT DO NOTHING;

-- API keys for public API access with rotation support
CREATE TABLE IF NOT EXISTS api_key (
    id                                   BIGINT        NOT NULL,
    partner_id                           BIGINT        NOT NULL,
    key_name                             VARCHAR(100)  NOT NULL,
    key_prefix                           CHAR(8)       NOT NULL,
    key_hash                             CHAR(64)      NOT NULL,
    scopes                               VARCHAR(500)  NOT NULL DEFAULT 'query',
    is_active                            BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at                           TIMESTAMP    ,
    last_used_at                         TIMESTAMP    ,
    user_id                              BIGINT       ,
    rotated_at                           TIMESTAMP    ,
    grace_expires_at                     TIMESTAMP    ,
    CONSTRAINT api_key_pk PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_api_key_hash ON api_key(key_hash);
CREATE INDEX IF NOT EXISTS idx_api_key_partner ON api_key(partner_id);

CREATE SEQUENCE IF NOT EXISTS api_key_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('api_key', 'id', 'api_key_seq') ON CONFLICT DO NOTHING;

-- One-time password codes for phone/email verification
CREATE TABLE IF NOT EXISTS user_otp (
    id                                   BIGINT        NOT NULL,
    user_id                              BIGINT        NOT NULL,
    code                                 VARCHAR(6)    NOT NULL,
    purpose                              VARCHAR(20)   NOT NULL,
    expires_at                           TIMESTAMP     NOT NULL,
    attempts                             INTEGER       NOT NULL DEFAULT 0,
    CONSTRAINT user_otp_pk PRIMARY KEY (id)
);

CREATE SEQUENCE IF NOT EXISTS user_otp_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('user_otp', 'id', 'user_otp_seq') ON CONFLICT DO NOTHING;

-- Social login provider links (Google, Apple)
CREATE TABLE IF NOT EXISTS user_social_provider (
    user_id                              BIGINT        NOT NULL,
    provider                             VARCHAR(20)   NOT NULL,
    provider_id                          VARCHAR(255)  NOT NULL,
    CONSTRAINT user_social_provider_pk PRIMARY KEY (user_id, provider)
);

-- Versioned privacy/terms/consent policy text registered for audit trail
CREATE TABLE IF NOT EXISTS consent_policy (
    id                                   BIGINT        NOT NULL,
    policy_type                          VARCHAR(30)   NOT NULL,
    region                               VARCHAR(10)   NOT NULL DEFAULT 'global',
    version                              VARCHAR(64)   NOT NULL,
    language                             VARCHAR(8)    NOT NULL DEFAULT 'en',
    content_url                          VARCHAR(500)  NOT NULL,
    content_sha256                       VARCHAR(64)   NOT NULL,
    effective_from                       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deprecated_at                        TIMESTAMP    ,
    CONSTRAINT consent_policy_pk PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS consent_policy_uq ON consent_policy(policy_type, region, version, language);

CREATE SEQUENCE IF NOT EXISTS consent_policy_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('consent_policy', 'id', 'consent_policy_seq') ON CONFLICT DO NOTHING;

-- Per-user consent decisions with full audit trail for PIPEDA/GDPR
CREATE TABLE IF NOT EXISTS consent_event (
    id                                   BIGINT        NOT NULL,
    user_id                              BIGINT       ,
    email_hash                           VARCHAR(64)  ,
    phone_hash                           VARCHAR(64)  ,
    consent_type                         VARCHAR(30)   NOT NULL,
    consented                            BOOLEAN       NOT NULL,
    policy_id                            BIGINT        NOT NULL,
    event_ref                            VARCHAR(64)  ,
    region                               VARCHAR(10)   NOT NULL,
    client_ip                            VARCHAR(45)  ,
    client_user_agent                    VARCHAR(500) ,
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT consent_event_pk PRIMARY KEY (id),
    CONSTRAINT consent_event_identity CHECK (user_id IS NOT NULL OR email_hash IS NOT NULL OR phone_hash IS NOT NULL)
);
CREATE INDEX IF NOT EXISTS idx_consent_event_user ON consent_event(user_id, consent_type);
CREATE INDEX IF NOT EXISTS idx_consent_event_email ON consent_event(email_hash, consent_type);
CREATE INDEX IF NOT EXISTS idx_consent_event_phone ON consent_event(phone_hash, consent_type);

CREATE SEQUENCE IF NOT EXISTS consent_event_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('consent_event', 'id', 'consent_event_seq') ON CONFLICT DO NOTHING;

-- Mobile device push-notification tokens (FCM / APNs via FCM)
CREATE TABLE IF NOT EXISTS device_token (
    id                                   BIGINT        NOT NULL,
    user_id                              BIGINT        NOT NULL,
    platform                             CHAR(1)       NOT NULL,
    token                                TEXT          NOT NULL,
    app_version                          VARCHAR(32)  ,
    device_model                         VARCHAR(64)  ,
    is_active                            BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at                         TIMESTAMP    ,
    CONSTRAINT device_token_pk PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS device_token_user_token_uq ON device_token(user_id, token);
CREATE INDEX IF NOT EXISTS idx_device_token_user_active ON device_token(user_id, is_active);

CREATE SEQUENCE IF NOT EXISTS device_token_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('device_token', 'id', 'device_token_seq') ON CONFLICT DO NOTHING;

-- OAuth 2.1 registered clients (Dynamic Client Registration)
CREATE TABLE IF NOT EXISTS oauth_client (
    id                                   BIGINT        NOT NULL,
    client_id                            VARCHAR(64)   NOT NULL,
    secret_hash                          VARCHAR(64)  ,
    client_name                          VARCHAR(200) ,
    redirect_uris                        VARCHAR(2000) NOT NULL,
    grant_types                          VARCHAR(500)  NOT NULL,
    scopes                               VARCHAR(1000),
    token_auth_method                    VARCHAR(40)   NOT NULL DEFAULT 'none',
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT oauth_client_pk PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_oauth_client_client_id ON oauth_client(client_id);

CREATE SEQUENCE IF NOT EXISTS oauth_client_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('oauth_client', 'id', 'oauth_client_seq') ON CONFLICT DO NOTHING;

-- Subscription plans (catalog). Per-interval prices live in subscription_plan_price.
CREATE TABLE IF NOT EXISTS subscription_plan (
    id                                   VARCHAR(20)   NOT NULL,
    caption                              VARCHAR(80)   NOT NULL,
    is_active                            BOOLEAN       NOT NULL DEFAULT TRUE,
    currency                             CHAR(3)       NOT NULL DEFAULT 'USD',
    activation_mode                      CHAR(1)       NOT NULL DEFAULT 'A',
    trial_days                           INTEGER      ,
    CONSTRAINT subscription_plan_pk PRIMARY KEY (id)
);

-- Single-use OAuth 2.1 authorization codes; partner_id is a denormalized snapshot for quota attribution
CREATE TABLE IF NOT EXISTS oauth_authorization_code (
    id                                   BIGINT        NOT NULL,
    code_hash                            CHAR(64)      NOT NULL,
    client_id                            VARCHAR(64)   NOT NULL,
    user_id                              BIGINT        NOT NULL,
    partner_id                           BIGINT       ,
    scopes                               VARCHAR(1000),
    redirect_uri                         VARCHAR(2000) NOT NULL,
    code_challenge                       VARCHAR(128)  NOT NULL,
    code_challenge_method                VARCHAR(10)   NOT NULL,
    resource                             VARCHAR(500) ,
    expires_at                           TIMESTAMP     NOT NULL,
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT oauth_authorization_code_pk PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_oauth_code_hash ON oauth_authorization_code(code_hash);

CREATE SEQUENCE IF NOT EXISTS oauth_authorization_code_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('oauth_authorization_code', 'id', 'oauth_authorization_code_seq') ON CONFLICT DO NOTHING;

-- Per-offer price points for a plan. Three independent axes — billing_cycle (how often charged), term_count×term_type (the commitment), and amount_minor (price for ONE term_type unit). The same plan can offer e.g. monthly, annual-paid-monthly, and annual-paid-once as distinct rows with their own provider_price_id.
CREATE TABLE IF NOT EXISTS subscription_plan_price (
    plan_id                              VARCHAR(20)   NOT NULL,
    billing_cycle                        CHAR(1)       NOT NULL,
    term_count                           INTEGER       NOT NULL DEFAULT 1,
    term_type                            CHAR(1)       NOT NULL DEFAULT 'M',
    amount_minor                         BIGINT        NOT NULL,
    currency                             CHAR(3)       NOT NULL DEFAULT 'USD',
    provider_price_id                    VARCHAR(64)  ,
    CONSTRAINT subscription_plan_price_pk PRIMARY KEY (plan_id, billing_cycle, term_type, term_count)
);

-- Quota-tracked resources (domains, API calls, etc.)
CREATE TABLE IF NOT EXISTS subscription_resource (
    id                                   VARCHAR(20)   NOT NULL,
    table_name                           VARCHAR(32)  ,
    status_column                        VARCHAR(32)  ,
    status_value                         VARCHAR(80)  ,
    date_column                          VARCHAR(32)  ,
    CONSTRAINT subscription_resource_pk PRIMARY KEY (id)
);

-- OAuth 2.1 refresh tokens (hashed) with rotation family for reuse-detection; partner_id is a denormalized snapshot
CREATE TABLE IF NOT EXISTS oauth_refresh_token (
    id                                   BIGINT        NOT NULL,
    token_hash                           CHAR(64)      NOT NULL,
    family_id                            VARCHAR(64)   NOT NULL,
    client_id                            VARCHAR(64)   NOT NULL,
    user_id                              BIGINT        NOT NULL,
    partner_id                           BIGINT       ,
    scopes                               VARCHAR(1000),
    resource                             VARCHAR(500) ,
    expires_at                           TIMESTAMP     NOT NULL,
    revoked_at                           TIMESTAMP    ,
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT oauth_refresh_token_pk PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_oauth_refresh_hash ON oauth_refresh_token(token_hash);
CREATE INDEX IF NOT EXISTS idx_oauth_refresh_family ON oauth_refresh_token(family_id);
CREATE INDEX IF NOT EXISTS idx_oauth_refresh_user ON oauth_refresh_token(user_id);

CREATE SEQUENCE IF NOT EXISTS oauth_refresh_token_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('oauth_refresh_token', 'id', 'oauth_refresh_token_seq') ON CONFLICT DO NOTHING;

-- Resource limits per subscription plan
CREATE TABLE IF NOT EXISTS subscription_quota (
    plan_id                              VARCHAR(20)   NOT NULL,
    resource_id                          VARCHAR(20)   NOT NULL,
    max_value                            BIGINT        NOT NULL,
    period_type                          CHAR(1)       NOT NULL DEFAULT 'M',
    CONSTRAINT subscription_quota_pk PRIMARY KEY (plan_id, resource_id)
);

-- OAuth / API-key credentials for partner connections to external providers
CREATE TABLE IF NOT EXISTS partner_credential (
    id                                   BIGINT        NOT NULL,
    partner_id                           BIGINT        NOT NULL,
    entity_id                            BIGINT        NOT NULL DEFAULT 0,
    provider                             VARCHAR(30)   NOT NULL,
    connection_type                      CHAR(1)       NOT NULL DEFAULT 'O',
    cred_ref                             TEXT          NOT NULL,
    api_endpoint                         VARCHAR(255) ,
    status                               CHAR(1)       NOT NULL DEFAULT 'A',
    rev                                  INTEGER       NOT NULL DEFAULT 0,
    lease_until                          TIMESTAMP    ,
    issued_at                            TIMESTAMP    ,
    last_checked                         TIMESTAMP    ,
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT partner_credential_pk PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS partner_credential_uq ON partner_credential(partner_id, entity_id, provider);

CREATE SEQUENCE IF NOT EXISTS partner_credential_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('partner_credential', 'id', 'partner_credential_seq') ON CONFLICT DO NOTHING;

-- Optional add-on features with separate pricing
CREATE TABLE IF NOT EXISTS subscription_addon (
    id                                   VARCHAR(20)   NOT NULL,
    caption                              VARCHAR(80)   NOT NULL,
    max_value                            BIGINT        NOT NULL,
    is_active                            BOOLEAN       NOT NULL DEFAULT TRUE,
    monthly_cost                         NUMERIC(18,2) NOT NULL,
    currency                             CHAR(3)       NOT NULL DEFAULT 'USD',
    billing_cycle                        CHAR(1)       NOT NULL DEFAULT 'M',
    term_count                           INTEGER       NOT NULL DEFAULT 1,
    term_type                            CHAR(1)       NOT NULL DEFAULT 'M',
    description                          VARCHAR(255) ,
    CONSTRAINT subscription_addon_pk PRIMARY KEY (id)
);

-- Single-use, TTL-bounded nonces (OAuth connect-state, JWT handoff). Natural key, no sequence.
CREATE TABLE IF NOT EXISTS auth_nonce (
    nonce                                VARCHAR(64)   NOT NULL,
    purpose                              VARCHAR(20)   NOT NULL,
    payload                              TEXT          NOT NULL,
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT auth_nonce_pk PRIMARY KEY (nonce)
);

-- Active plan subscriptions per business partner
CREATE TABLE IF NOT EXISTS partner_plan_subscription (
    partner_id                           BIGINT        NOT NULL,
    plan_id                              VARCHAR(20)   NOT NULL,
    begda                                TIMESTAMP     NOT NULL,
    endda                                TIMESTAMP    ,
    monthly_cost                         NUMERIC(18,2) NOT NULL,
    currency                             CHAR(3)       NOT NULL,
    status                               CHAR(1)       NOT NULL,
    auto_renew                           BOOLEAN       NOT NULL DEFAULT TRUE,
    provider_subscription_id             VARCHAR(64)  ,
    billing_cycle                        CHAR(1)      ,
    term_count                           INTEGER      ,
    term_type                            CHAR(1)      ,
    amount_minor                         BIGINT       ,
    renewal_date                         TIMESTAMP    ,
    next_charge_date                     TIMESTAMP    ,
    cancelled_at                         TIMESTAMP    ,
    effective_cancel_date                TIMESTAMP    ,
    trial_end                            TIMESTAMP    ,
    seats                                INTEGER      ,
    CONSTRAINT partner_plan_subscription_pk PRIMARY KEY (partner_id, plan_id, begda)
);
CREATE INDEX IF NOT EXISTS idx_partner_plan_subscription_provider_sub ON partner_plan_subscription(provider_subscription_id);

-- Active add-on subscriptions per business partner
CREATE TABLE IF NOT EXISTS partner_addon_subscription (
    partner_id                           BIGINT        NOT NULL,
    addon_id                             VARCHAR(20)   NOT NULL,
    auto_increase                        BOOLEAN       NOT NULL DEFAULT FALSE,
    begda                                TIMESTAMP     NOT NULL,
    endda                                TIMESTAMP    ,
    monthly_cost                         NUMERIC(18,2) NOT NULL,
    currency                             CHAR(3)       NOT NULL,
    status                               CHAR(1)       NOT NULL,
    auto_renew                           BOOLEAN       NOT NULL DEFAULT TRUE,
    billing_cycle                        CHAR(1)      ,
    term_count                           INTEGER      ,
    term_type                            CHAR(1)      ,
    amount_minor                         BIGINT       ,
    renewal_date                         TIMESTAMP    ,
    next_charge_date                     TIMESTAMP    ,
    CONSTRAINT partner_addon_subscription_pk PRIMARY KEY (partner_id, addon_id, begda)
);

-- Resource usage tracking for quota enforcement
CREATE TABLE IF NOT EXISTS usage_ledger (
    partner_id                           BIGINT        NOT NULL,
    usage_time                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resource_name                        VARCHAR(50)   NOT NULL,
    amount                               BIGINT        NOT NULL,
    notes                                VARCHAR(255) ,
    CONSTRAINT usage_ledger_pk PRIMARY KEY (partner_id, usage_time)
);
CREATE INDEX IF NOT EXISTS idx_usage_ledger_quota ON usage_ledger(partner_id, resource_name, usage_time);

-- Raw inbound payment provider webhooks — idempotency + audit
CREATE TABLE IF NOT EXISTS payment_webhook_log (
    id                                   BIGINT        NOT NULL,
    provider                             VARCHAR(30)   NOT NULL,
    event_id                             VARCHAR(255)  NOT NULL,
    event_type                           VARCHAR(100)  NOT NULL,
    processing_status                    CHAR(1)       NOT NULL DEFAULT 'R',
    error_message                        TEXT         ,
    request_id                           TEXT         ,
    raw_payload                          TEXT         ,
    replay_attempts                      INTEGER       NOT NULL DEFAULT 0,
    received_at                          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at                         TIMESTAMP    ,
    last_claimed_at                      TIMESTAMP    ,
    CONSTRAINT payment_webhook_log_pk PRIMARY KEY (id),
    CONSTRAINT chk_payment_webhook_status CHECK (processing_status IN ('R', 'P', 'F', 'D', 'S', 'L')),
    CONSTRAINT chk_payment_webhook_replay_attempts CHECK (replay_attempts >= 0)
);
CREATE UNIQUE INDEX IF NOT EXISTS payment_webhook_log_uq ON payment_webhook_log(provider, event_id);
CREATE INDEX IF NOT EXISTS idx_payment_webhook_replay ON payment_webhook_log(processing_status, id);

CREATE SEQUENCE IF NOT EXISTS payment_webhook_log_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('payment_webhook_log', 'id', 'payment_webhook_log_seq') ON CONFLICT DO NOTHING;

-- Stored payment methods per business partner (provider customer tokens)
CREATE TABLE IF NOT EXISTS payment_method (
    id                                   BIGINT        NOT NULL,
    partner_id                           BIGINT        NOT NULL,
    provider                             VARCHAR(30)   NOT NULL,
    provider_token                       VARCHAR(255)  NOT NULL,
    method_type                          VARCHAR(20)   NOT NULL,
    is_default                           BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payment_method_pk PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_payment_method_default ON payment_method(partner_id, is_default);

CREATE SEQUENCE IF NOT EXISTS payment_method_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('payment_method', 'id', 'payment_method_seq') ON CONFLICT DO NOTHING;

-- Versioned (user, partner) bank account details for out-bound payouts.
-- Owned by keel/payout. Raw routing details live with the provider
-- (Airwallex / Stripe Connect / Wise); this row carries only the
-- provider handle plus tax/correspondence metadata.
-- Rows are versions: identity-bearing changes (provider, account,
-- tax id, holder, country, currency, address) close the active row
-- (status='S', superseded_at) and insert a new one; onboarding
-- lifecycle fields mutate the active row in place. At most one
-- active row per (user_id, partner_id) — partial unique index on
-- PostgreSQL, service-enforced on MySQL.
CREATE TABLE IF NOT EXISTS user_bank_info (
    id                                   BIGINT        NOT NULL,
    user_id                              BIGINT        NOT NULL,
    partner_id                           BIGINT        NOT NULL,
    country_code                         CHAR(2)       NOT NULL,
    currency                             CHAR(3)       NOT NULL,
    account_holder_name                  VARCHAR(200)  NOT NULL,
    billing_address                      TEXT          NOT NULL,
    tax_id_type                          CHAR(1)       NOT NULL,
    tax_id_encrypted                     BYTEA         NOT NULL,
    provider                             CHAR(2)       NOT NULL,
    provider_account_id                  VARCHAR(100) ,
    provider_agreement                   BOOLEAN       NOT NULL DEFAULT FALSE,
    provider_onboarded_at                TIMESTAMP    ,
    status                               CHAR(1)       NOT NULL DEFAULT 'A',
    superseded_at                        TIMESTAMP    ,
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_bank_info_pk PRIMARY KEY (id),
    CONSTRAINT chk_user_bank_info_lifecycle CHECK ((status = 'A' AND superseded_at IS NULL) OR (status = 'S' AND superseded_at IS NOT NULL))
);
CREATE UNIQUE INDEX IF NOT EXISTS user_bank_info_active_uq ON user_bank_info(user_id, partner_id) WHERE status = 'A';
CREATE UNIQUE INDEX IF NOT EXISTS user_bank_info_id_partner_uq ON user_bank_info(id, partner_id);
CREATE INDEX IF NOT EXISTS idx_user_bank_info_partner ON user_bank_info(partner_id);

CREATE SEQUENCE IF NOT EXISTS user_bank_info_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('user_bank_info', 'id', 'user_bank_info_seq') ON CONFLICT DO NOTHING;

-- Saved payment methods for end users (cards, wallets, bank accounts).
-- Distinct from `payment_method`, which is partner-scoped for SaaS
-- billing — this row is per (user_id), the consumer cards a user has
-- on file for in-bound payments. provider_token is the provider's
-- reusable handle (Stripe PaymentMethod id, SetupIntent id, etc.);
-- raw card numbers / IBANs / SWIFT never land here.
CREATE TABLE IF NOT EXISTS user_payment_method (
    id                                   BIGINT        NOT NULL,
    user_id                              BIGINT        NOT NULL,
    method_type                          VARCHAR(20)   NOT NULL,
    provider                             VARCHAR(30)   NOT NULL,
    provider_token                       VARCHAR(255)  NOT NULL,
    last_four                            VARCHAR(4)   ,
    brand                                VARCHAR(20)  ,
    expiry_month                         SMALLINT     ,
    expiry_year                          SMALLINT     ,
    currency                             CHAR(3)       NOT NULL DEFAULT 'USD',
    is_default                           BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_payment_method_pk PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_user_payment_method_user ON user_payment_method(user_id, is_default);

CREATE SEQUENCE IF NOT EXISTS user_payment_method_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('user_payment_method', 'id', 'user_payment_method_seq') ON CONFLICT DO NOTHING;

-- Per-table custom actions surfaced as buttons in CRUD UIs. Each row
-- registers ONE action; the downstream application must also (a) seed
-- the matching authorization_object + authorization_object_action rows
-- so roles can grant access, and (b) register an HTTP handler at the
-- conventional URL POST /<rest_prefix>/<table_name>/<action_name>.
-- 
-- authorization_object.id mirrors the uppercased table name and
-- authorization_object_action.action mirrors the uppercased action_name
-- — gives each table its own action namespace so the same action name
-- ('assign', 'enable', 'calculate') can mean different things on
-- different tables without a shared auth dimension.
-- 
-- record_specific=TRUE  → button renders next to per-row edit/delete.
-- record_specific=FALSE → button renders next to the "New Record"
--                         control at the table-level toolbar.
-- 
-- Reserved action_name values that collide with generic CRUD subpaths
-- (list / get / post / delete / get-paginated) are rejected at REST
-- service boot.
CREATE TABLE IF NOT EXISTS table_action (
    table_name                           VARCHAR(80)   NOT NULL,
    action_name                          VARCHAR(30)   NOT NULL,
    caption                              VARCHAR(80)   NOT NULL,
    icon                                 VARCHAR(40)  ,
    record_specific                      BOOLEAN       NOT NULL DEFAULT FALSE,
    action_kind                          CHAR(1)       NOT NULL DEFAULT 'P',
    method_name                          VARCHAR(80)  ,
    display_order                        SMALLINT      NOT NULL DEFAULT 10,
    confirm_message                      VARCHAR(200) ,
    CONSTRAINT table_action_pk PRIMARY KEY (table_name, action_name)
);
CREATE INDEX IF NOT EXISTS idx_table_action_table ON table_action(table_name);

-- Billing invoices per partner (provider-issued or self-scheduled)
CREATE TABLE IF NOT EXISTS invoice (
    id                                   BIGINT        NOT NULL,
    partner_id                           BIGINT        NOT NULL,
    invoice_number                       VARCHAR(30)   NOT NULL,
    status                               CHAR(1)       NOT NULL DEFAULT 'D',
    subtotal                             NUMERIC(20,4) NOT NULL,
    tax                                  NUMERIC(20,4) NOT NULL DEFAULT 0.00,
    total                                NUMERIC(20,4) NOT NULL,
    total_minor                          BIGINT        NOT NULL,
    currency                             CHAR(3)       NOT NULL DEFAULT 'USD',
    issued_at                            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    due_at                               TIMESTAMP    ,
    paid_at                              TIMESTAMP    ,
    pdf_storage_path                     VARCHAR(500) ,
    provider_invoice_id                  VARCHAR(255) ,
    provider_charge_id                   VARCHAR(255) ,
    attempt_count                        INTEGER       NOT NULL DEFAULT 0,
    next_attempt_at                      TIMESTAMP    ,
    last_error                           TEXT         ,
    CONSTRAINT invoice_pk PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_invoice_number ON invoice(invoice_number);
CREATE INDEX IF NOT EXISTS idx_invoice_partner ON invoice(partner_id);
CREATE UNIQUE INDEX IF NOT EXISTS invoice_id_partner_uq ON invoice(id, partner_id);
CREATE UNIQUE INDEX IF NOT EXISTS invoice_id_currency_uq ON invoice(id, currency);

CREATE SEQUENCE IF NOT EXISTS invoice_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('invoice', 'id', 'invoice_seq') ON CONFLICT DO NOTHING;

-- Line items for an invoice — domain-neutral finance data only.
-- amount_minor is the authoritative integer minor-unit amount (amount
-- stays for display) and has NO default: writers must supply it.
-- service_from / service_to (inclusive / exclusive) bound the
-- covered-service period for period-scoped consumers (proration,
-- partial refunds). What a line sells lives in domain extension tables
-- (e.g. subscription_invoice_line), never here.
CREATE TABLE IF NOT EXISTS invoice_line (
    invoice_id                           BIGINT        NOT NULL,
    seq                                  INTEGER       NOT NULL,
    description                          VARCHAR(200)  NOT NULL,
    quantity                             INTEGER       NOT NULL DEFAULT 1,
    unit_price                           NUMERIC(20,4) NOT NULL,
    amount                               NUMERIC(20,4) NOT NULL,
    amount_minor                         BIGINT        NOT NULL,
    service_from                         TIMESTAMP    ,
    service_to                           TIMESTAMP    ,
    CONSTRAINT invoice_line_pk PRIMARY KEY (invoice_id, seq)
);

-- Partner ↔ provider-customer token, one row per (partner, provider). Its own
-- table (not a method_type='customer' row in payment_method) so payment_method
-- holds only real chargeable methods. Used for billing-portal sessions and
-- recurring-invoice attribution (the reverse token→partner lookup).
CREATE TABLE IF NOT EXISTS partner_billing_customer (
    partner_id                           BIGINT        NOT NULL,
    provider                             VARCHAR(30)   NOT NULL,
    customer_token                       VARCHAR(255)  NOT NULL,
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT partner_billing_customer_pk PRIMARY KEY (partner_id, provider)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_partner_billing_customer_token ON partner_billing_customer(provider, customer_token);

-- Subscription-domain extension of a generic invoice line: names the
-- plan or add-on the line bills. Exactly one of plan_id / addon_id is
-- set (check-enforced). Lines with no row here are non-subscription
-- charges (fees, adjustments). Keeps invoice / invoice_line
-- domain-neutral for finance purposes.
CREATE TABLE IF NOT EXISTS subscription_invoice_line (
    invoice_id                           BIGINT        NOT NULL,
    invoice_line_seq                     INTEGER       NOT NULL,
    plan_id                              VARCHAR(20)  ,
    addon_id                             VARCHAR(20)  ,
    CONSTRAINT subscription_invoice_line_pk PRIMARY KEY (invoice_id, invoice_line_seq),
    CONSTRAINT chk_sub_invoice_line_one_of CHECK ((plan_id IS NOT NULL AND addon_id IS NULL) OR (plan_id IS NULL AND addon_id IS NOT NULL))
);

-- Completed/failed/refunded payment transactions per partner —
-- domain-neutral finance data: a payment settles an invoice, whatever
-- the invoice sells. What was bought resolves through the invoice's
-- lines and their domain extension tables, never through columns here.
CREATE TABLE IF NOT EXISTS payment_record (
    id                                   BIGINT        NOT NULL,
    partner_id                           BIGINT       ,
    provider                             VARCHAR(30)   NOT NULL,
    provider_payment_id                  VARCHAR(255) ,
    provider_event_type                  VARCHAR(100) ,
    provider_charge_id                   VARCHAR(255) ,
    amount                               NUMERIC(20,4) NOT NULL,
    amount_minor                         BIGINT        NOT NULL,
    currency                             CHAR(3)       NOT NULL,
    invoice_id                           BIGINT       ,
    payment_status                       CHAR(1)       NOT NULL,
    paid_at                              TIMESTAMP    ,
    raw_payload                          TEXT         ,
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payment_record_pk PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_payment_record_partner ON payment_record(partner_id, paid_at);
CREATE INDEX IF NOT EXISTS idx_payment_record_provider_charge ON payment_record(provider, provider_charge_id);
CREATE UNIQUE INDEX IF NOT EXISTS payment_record_provider_uq ON payment_record(provider, provider_payment_id) WHERE provider_payment_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS payment_record_id_invoice_uq ON payment_record(id, invoice_id);

CREATE SEQUENCE IF NOT EXISTS payment_record_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('payment_record', 'id', 'payment_record_seq') ON CONFLICT DO NOTHING;

-- Durable allocation of one payment (or refund) to one invoice line in
-- integer minor units. entry_type P allocates a collected payment
-- (positive), R a refund (negative) — check-enforced. Currency is not
-- repeated here: it is authoritative on the referenced payment/invoice.
-- Consumers that recognize value per line (commission ledgers, revenue
-- reporting, partial-refund processing) key on this row rather than
-- reconstructing identity from payment + invoice + line columns.
CREATE TABLE IF NOT EXISTS invoice_line_payment (
    id                                   BIGINT        NOT NULL,
    payment_record_id                    BIGINT        NOT NULL,
    invoice_id                           BIGINT        NOT NULL,
    invoice_line_seq                     INTEGER       NOT NULL,
    entry_type                           CHAR(1)       NOT NULL DEFAULT 'P',
    amount_minor                         BIGINT        NOT NULL,
    provider_ref                         VARCHAR(255) ,
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT invoice_line_payment_pk PRIMARY KEY (id),
    CONSTRAINT chk_inv_line_pmt_sign CHECK ((entry_type = 'P' AND amount_minor > 0) OR (entry_type = 'R' AND amount_minor < 0))
);
CREATE UNIQUE INDEX IF NOT EXISTS inv_line_pmt_ref_uq ON invoice_line_payment(provider_ref) WHERE provider_ref IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_inv_line_pmt_payment ON invoice_line_payment(payment_record_id);
CREATE INDEX IF NOT EXISTS idx_inv_line_pmt_line ON invoice_line_payment(invoice_id, invoice_line_seq);

CREATE SEQUENCE IF NOT EXISTS invoice_line_payment_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('invoice_line_payment', 'id', 'invoice_line_payment_seq') ON CONFLICT DO NOTHING;

-- Raw inbound payout-provider webhooks — durable event-id idempotency +
-- audit for account-lifecycle and transfer-lifecycle events. Financial
-- events must never rely on a process-local or expiring cache; the
-- UNIQUE (provider, event_id) index is the authoritative race guard.
CREATE TABLE IF NOT EXISTS payout_webhook_log (
    id                                   BIGINT        NOT NULL,
    provider                             CHAR(2)       NOT NULL,
    event_id                             VARCHAR(255)  NOT NULL,
    event_type                           VARCHAR(100)  NOT NULL,
    provider_account_id                  VARCHAR(100) ,
    provider_transfer_id                 VARCHAR(255) ,
    processing_status                    CHAR(1)       NOT NULL DEFAULT 'R',
    error_message                        TEXT         ,
    raw_payload                          TEXT         ,
    received_at                          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at                         TIMESTAMP    ,
    CONSTRAINT payout_webhook_log_pk PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS payout_webhook_log_uq ON payout_webhook_log(provider, event_id);
CREATE INDEX IF NOT EXISTS idx_payout_webhook_transfer ON payout_webhook_log(provider_transfer_id);

CREATE SEQUENCE IF NOT EXISTS payout_webhook_log_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('payout_webhook_log', 'id', 'payout_webhook_log_seq') ON CONFLICT DO NOTHING;

-- Transactional outbox — events captured in the same tx as a domain write, then drained by a lease worker for reliable at-least-once delivery
CREATE TABLE IF NOT EXISTS outbox_event (
    id                                   BIGINT        NOT NULL,
    partner_id                           BIGINT       ,
    aggregate_type                       VARCHAR(64)   NOT NULL,
    aggregate_id                         VARCHAR(128)  NOT NULL,
    event_type                           VARCHAR(64)   NOT NULL,
    payload                              TEXT         ,
    status                               CHAR(1)       NOT NULL DEFAULT 'P',
    attempts                             INTEGER       NOT NULL DEFAULT 0,
    available_at                         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lease_until                          TIMESTAMP    ,
    lease_token                          BIGINT       ,
    last_error                           TEXT         ,
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT outbox_event_pk PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_outbox_drain ON outbox_event(status, available_at);
CREATE INDEX IF NOT EXISTS idx_outbox_aggregate ON outbox_event(aggregate_type, aggregate_id);

CREATE SEQUENCE IF NOT EXISTS outbox_event_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('outbox_event', 'id', 'outbox_event_seq') ON CONFLICT DO NOTHING;

-- Catalog of runtime configuration flags loaded into common.BaseConfig at startup. Non-secret values only; store a secret NAME here, never secret material.
CREATE TABLE IF NOT EXISTS application_config_flag (
    id                                   VARCHAR(80)   NOT NULL,
    data_type                            VARCHAR(20)   NOT NULL DEFAULT 'string',
    needs_restart                        BOOLEAN       NOT NULL DEFAULT FALSE,
    default_value                        TEXT         ,
    description                          TEXT         ,
    CONSTRAINT application_config_flag_pk PRIMARY KEY (id)
);

-- Per-node assigned values for application_config_flag. node_id identifies the runtime node/process (matched against --node_id). Most single-node deployments use 0; multi-node deployments assign values per node. Missing rows fall back to application_config_flag.default_value.
CREATE TABLE IF NOT EXISTS application_config_value (
    node_id                              INTEGER       NOT NULL DEFAULT 0,
    flag_id                              VARCHAR(80)   NOT NULL,
    assigned_value                       TEXT         ,
    CONSTRAINT application_config_value_pk PRIMARY KEY (node_id, flag_id)
);

-- Agency capability and approval state for a business partner. Referral
-- commission is available to every approved agency; wholesale_allowed is a
-- permission for per-client wholesale assignments, not a global billing mode.
CREATE TABLE IF NOT EXISTS agency_profile (
    agency_partner_id                    BIGINT        NOT NULL,
    wholesale_allowed                    BOOLEAN       NOT NULL DEFAULT FALSE,
    default_commission_rate_bp           INTEGER      ,
    approved_at                          TIMESTAMP    ,
    suspended                            BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT agency_profile_pk PRIMARY KEY (agency_partner_id),
    CONSTRAINT chk_agency_profile_rate CHECK (default_commission_rate_bp IS NULL OR (default_commission_rate_bp > 0 AND default_commission_rate_bp <= 10000))
);

-- An agency's staged and invited prospective clients. Prospects need not be
-- users or partners yet; client_partner_id is populated only after the
-- invitee has a partner and explicitly accepts the delegation.
CREATE TABLE IF NOT EXISTS agency_client_invitation (
    id                                   BIGINT        NOT NULL,
    agency_partner_id                    BIGINT        NOT NULL,
    client_name                          VARCHAR(200)  NOT NULL,
    client_email                         VARCHAR(255) ,
    client_website                       VARCHAR(255) ,
    invite_token                         VARCHAR(64)  ,
    status                               CHAR(1)       NOT NULL DEFAULT 'S',
    client_partner_id                    BIGINT       ,
    accepted_by                          BIGINT       ,
    invited_at                           TIMESTAMP    ,
    accepted_at                          TIMESTAMP    ,
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT agency_client_invitation_pk PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS invitation_token_uq ON agency_client_invitation(invite_token);
CREATE INDEX IF NOT EXISTS idx_agency_client_invitation ON agency_client_invitation(agency_partner_id, status);

CREATE SEQUENCE IF NOT EXISTS agency_client_invitation_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('agency_client_invitation', 'id', 'agency_client_invitation_seq') ON CONFLICT DO NOTHING;

-- Owner-granted, revocable partner-to-partner management delegation. The
-- generic table permits several active rows for one client partner so an app
-- extension can scope them to different managed entities (for example, each
-- business). The direct-partner base service enforces one active row itself.
CREATE TABLE IF NOT EXISTS agency_client_delegation (
    id                                   BIGINT        NOT NULL,
    client_partner_id                    BIGINT        NOT NULL,
    agency_partner_id                    BIGINT        NOT NULL,
    granted_by                           BIGINT        NOT NULL,
    status                               CHAR(1)       NOT NULL DEFAULT 'A',
    granted_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_at                           TIMESTAMP    ,
    revoked_by                           BIGINT       ,
    CONSTRAINT agency_client_delegation_pk PRIMARY KEY (id),
    CONSTRAINT chk_delegation_distinct CHECK (client_partner_id <> agency_partner_id),
    CONSTRAINT chk_delegation_lifecycle CHECK ((status = 'A' AND revoked_at IS NULL AND revoked_by IS NULL) OR (status = 'R' AND revoked_at IS NOT NULL AND revoked_by IS NOT NULL))
);
CREATE UNIQUE INDEX IF NOT EXISTS delegation_episode_uq ON agency_client_delegation(agency_partner_id, client_partner_id, granted_at);
CREATE INDEX IF NOT EXISTS idx_agency_client_delegation_client ON agency_client_delegation(client_partner_id, status);
CREATE INDEX IF NOT EXISTS idx_agency_client_delegation_agency ON agency_client_delegation(agency_partner_id, status);

CREATE SEQUENCE IF NOT EXISTS agency_client_delegation_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('agency_client_delegation', 'id', 'agency_client_delegation_seq') ON CONFLICT DO NOTHING;

-- Effective-dated referral (R) or wholesale (W) model per delegation. The
-- partial unique index permits only one open row without a database extension;
-- services close then insert atomically and validate historical intervals.
CREATE TABLE IF NOT EXISTS agency_client_billing (
    id                                   BIGINT        NOT NULL,
    client_delegation_id                 BIGINT        NOT NULL,
    billing_model                        CHAR(1)       NOT NULL,
    effective_from                       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    effective_to                         TIMESTAMP    ,
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT agency_client_billing_pk PRIMARY KEY (id),
    CONSTRAINT chk_agency_client_billing_model CHECK (billing_model IN ('R', 'W')),
    CONSTRAINT chk_agency_client_billing_period CHECK (effective_to IS NULL OR effective_to > effective_from)
);
CREATE UNIQUE INDEX IF NOT EXISTS agency_client_billing_open_uq ON agency_client_billing(client_delegation_id) WHERE effective_to IS NULL;
CREATE INDEX IF NOT EXISTS idx_agency_client_billing_period ON agency_client_billing(client_delegation_id, effective_from);

CREATE SEQUENCE IF NOT EXISTS agency_client_billing_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('agency_client_billing', 'id', 'agency_client_billing_seq') ON CONFLICT DO NOTHING;

-- Selects the exact active user_bank_info version used for an agency's
-- commission payouts. The composite FK proves the destination belongs to the
-- agency; user and provider are derived from user_bank_info, not duplicated.
CREATE TABLE IF NOT EXISTS agency_payout_profile (
    agency_partner_id                    BIGINT        NOT NULL,
    user_bank_info_id                    BIGINT        NOT NULL,
    status                               CHAR(1)       NOT NULL DEFAULT 'A',
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT agency_payout_profile_pk PRIMARY KEY (agency_partner_id),
    CONSTRAINT chk_agency_payout_profile_status CHECK (status IN ('A', 'I'))
);

-- Percentage commission rate frozen per agency/client at the client's first
-- earning. Resolution prefers agency_profile.default_commission_rate_bp and
-- otherwise uses application_config_value/default_commission_rate_bp.
CREATE TABLE IF NOT EXISTS agency_client_rate (
    agency_partner_id                    BIGINT        NOT NULL,
    client_partner_id                    BIGINT        NOT NULL,
    commission_rate_bp                   INTEGER       NOT NULL,
    first_earned_at                      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT agency_client_rate_pk PRIMARY KEY (agency_partner_id, client_partner_id),
    CONSTRAINT chk_agency_client_rate CHECK (commission_rate_bp > 0 AND commission_rate_bp <= 10000)
);

-- Append-only earning/reversal ledger. The frozen percentage is snapshotted
-- in applied_rate_bp; only payout lifecycle status changes after insertion.
-- Codes are column-scoped: entry_type E=earning/R=reversal; status H=held,
-- P=payable, R=reserved, D=disbursed, O=offset/settled reversal.
CREATE TABLE IF NOT EXISTS agency_commission (
    id                                   BIGINT        NOT NULL,
    client_billing_id                    BIGINT        NOT NULL,
    invoice_line_payment_id              BIGINT        NOT NULL,
    earning_period_start                 TIMESTAMP     NOT NULL,
    earning_period_end                   TIMESTAMP     NOT NULL,
    gross_amount_minor                   BIGINT        NOT NULL,
    commission_amount_minor              BIGINT        NOT NULL,
    applied_rate_bp                      INTEGER       NOT NULL,
    currency                             CHAR(3)       NOT NULL,
    entry_type                           CHAR(1)       NOT NULL,
    status                               CHAR(1)       NOT NULL DEFAULT 'H',
    reversal_of_id                       BIGINT       ,
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    earned_at                            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT agency_commission_pk PRIMARY KEY (id),
    CONSTRAINT chk_agency_commission_entry CHECK ((entry_type = 'E' AND gross_amount_minor > 0 AND commission_amount_minor > 0 AND reversal_of_id IS NULL) OR (entry_type = 'R' AND gross_amount_minor < 0 AND commission_amount_minor < 0 AND reversal_of_id IS NOT NULL)),
    CONSTRAINT chk_agency_commission_period CHECK (earning_period_end > earning_period_start),
    CONSTRAINT chk_agency_commission_rate CHECK (applied_rate_bp > 0 AND applied_rate_bp <= 10000)
);
CREATE UNIQUE INDEX IF NOT EXISTS agency_commission_source_uq ON agency_commission(invoice_line_payment_id, earning_period_start) WHERE entry_type = 'E';
CREATE INDEX IF NOT EXISTS idx_agency_commission_status ON agency_commission(status, currency);
CREATE INDEX IF NOT EXISTS idx_agency_commission_billing ON agency_commission(client_billing_id);

CREATE SEQUENCE IF NOT EXISTS agency_commission_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('agency_commission', 'id', 'agency_commission_seq') ON CONFLICT DO NOTHING;

-- One aggregate payout per agency, currency, destination, and selection
-- cutoff. Destination fields are immutable snapshots. user_id is derived
-- through user_bank_info and is deliberately not duplicated here. Status:
-- C=created, P=provider-pending, D=disbursed, F=failed, M=manual review,
-- R=returned, V=reversed. Codes are scoped to this column.
CREATE TABLE IF NOT EXISTS agency_payout (
    id                                   BIGINT        NOT NULL,
    agency_partner_id                    BIGINT        NOT NULL,
    user_bank_info_id                    BIGINT        NOT NULL,
    amount_minor                         BIGINT        NOT NULL,
    currency                             CHAR(3)       NOT NULL,
    provider                             CHAR(2)       NOT NULL,
    provider_account_id                  VARCHAR(100)  NOT NULL,
    selection_cutoff_at                  TIMESTAMP     NOT NULL,
    idempotency_key                      VARCHAR(100)  NOT NULL,
    provider_transfer_id                 VARCHAR(255) ,
    provider_funding_id                  VARCHAR(255) ,
    status                               CHAR(1)       NOT NULL DEFAULT 'C',
    attempt_count                        INTEGER       NOT NULL DEFAULT 0,
    attempted_at                         TIMESTAMP    ,
    next_attempt_at                      TIMESTAMP    ,
    paid_at                              TIMESTAMP    ,
    failure_message                      TEXT         ,
    created_at                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT agency_payout_pk PRIMARY KEY (id),
    CONSTRAINT chk_agency_payout_amount CHECK (amount_minor > 0)
);
CREATE UNIQUE INDEX IF NOT EXISTS agency_payout_idem_uq ON agency_payout(idempotency_key);
CREATE UNIQUE INDEX IF NOT EXISTS agency_payout_transfer_uq ON agency_payout(provider, provider_transfer_id) WHERE provider_transfer_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_agency_payout_funding ON agency_payout(provider_funding_id) WHERE provider_funding_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS agency_payout_cycle_uq ON agency_payout(agency_partner_id, currency, provider_account_id, selection_cutoff_at) WHERE status <> 'F';

CREATE SEQUENCE IF NOT EXISTS agency_payout_seq INCREMENT BY 1 START WITH 1;
INSERT INTO table_sequence_usage (table_name, column_name, sequence_name) VALUES ('agency_payout', 'id', 'agency_payout_seq') ON CONFLICT DO NOTHING;

-- Allocation of commission ledger entries to aggregate payouts. A null
-- released_at marks the live allocation; terminal failure releases the line.
CREATE TABLE IF NOT EXISTS agency_payout_line (
    payout_id                            BIGINT        NOT NULL,
    commission_id                        BIGINT        NOT NULL,
    amount_minor                         BIGINT        NOT NULL,
    released_at                          TIMESTAMP    ,
    CONSTRAINT agency_payout_line_pk PRIMARY KEY (payout_id, commission_id),
    CONSTRAINT chk_agency_payout_line_amount CHECK (amount_minor <> 0)
);
CREATE UNIQUE INDEX IF NOT EXISTS agency_payout_line_live_uq ON agency_payout_line(commission_id) WHERE released_at IS NULL;

-- Foreign keys (emitted post-CREATE so order doesn't matter)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'constant_values' AND table_name = 'constant_value'
  ) THEN
    ALTER TABLE constant_value ADD CONSTRAINT constant_values FOREIGN KEY (constant_id) REFERENCES constant_header(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'constant_lookups' AND table_name = 'constant_lookup'
  ) THEN
    ALTER TABLE constant_lookup ADD CONSTRAINT constant_lookups FOREIGN KEY (constant_id) REFERENCES constant_header(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'rest_api_children' AND table_name = 'rest_api_child'
  ) THEN
    ALTER TABLE rest_api_child ADD CONSTRAINT rest_api_children FOREIGN KEY (api_id) REFERENCES rest_api_header(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'rest_api_lookups' AND table_name = 'rest_api_child'
  ) THEN
    ALTER TABLE rest_api_child ADD CONSTRAINT rest_api_lookups FOREIGN KEY (constraint_name) REFERENCES foreign_key_lookup(constraint_name);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'rest_report_params' AND table_name = 'rest_report_param'
  ) THEN
    ALTER TABLE rest_report_param ADD CONSTRAINT rest_report_params FOREIGN KEY (report_id) REFERENCES rest_report_header(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'rest_report_param_constants' AND table_name = 'rest_report_param'
  ) THEN
    ALTER TABLE rest_report_param ADD CONSTRAINT rest_report_param_constants FOREIGN KEY (constant_id) REFERENCES constant_header(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'application_menu_items' AND table_name = 'application_menu_item'
  ) THEN
    ALTER TABLE application_menu_item ADD CONSTRAINT application_menu_items FOREIGN KEY (menu_id) REFERENCES application_menu(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'authorization_object_actions' AND table_name = 'authorization_object_action'
  ) THEN
    ALTER TABLE authorization_object_action ADD CONSTRAINT authorization_object_actions FOREIGN KEY (authorization_object_id) REFERENCES authorization_object(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'states' AND table_name = 'state'
  ) THEN
    ALTER TABLE state ADD CONSTRAINT states FOREIGN KEY (country_id) REFERENCES country(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'counties' AND table_name = 'county'
  ) THEN
    ALTER TABLE county ADD CONSTRAINT counties FOREIGN KEY (country_id, state_id) REFERENCES state(country_id, id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'authorization_role_permissions' AND table_name = 'authorization_role_permission'
  ) THEN
    ALTER TABLE authorization_role_permission ADD CONSTRAINT authorization_role_permissions FOREIGN KEY (role_id) REFERENCES authorization_role(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'permitted_object_action' AND table_name = 'authorization_role_permission'
  ) THEN
    ALTER TABLE authorization_role_permission ADD CONSTRAINT permitted_object_action FOREIGN KEY (authorization_object_id, action) REFERENCES authorization_object_action(authorization_object_id, action);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'user_permissions' AND table_name = 'user_permission'
  ) THEN
    ALTER TABLE user_permission ADD CONSTRAINT user_permissions FOREIGN KEY (user_id) REFERENCES user_account(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'permitted_users' AND table_name = 'user_permission'
  ) THEN
    ALTER TABLE user_permission ADD CONSTRAINT permitted_users FOREIGN KEY (role_id) REFERENCES authorization_role(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'user_historic_actions' AND table_name = 'user_account_history'
  ) THEN
    ALTER TABLE user_account_history ADD CONSTRAINT user_historic_actions FOREIGN KEY (user_id) REFERENCES user_account(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'partner_users' AND table_name = 'partner_user'
  ) THEN
    ALTER TABLE partner_user ADD CONSTRAINT partner_users FOREIGN KEY (partner_id) REFERENCES business_partner(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'user_partners' AND table_name = 'partner_user'
  ) THEN
    ALTER TABLE partner_user ADD CONSTRAINT user_partners FOREIGN KEY (user_id) REFERENCES user_account(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'partner_addresses' AND table_name = 'partner_address'
  ) THEN
    ALTER TABLE partner_address ADD CONSTRAINT partner_addresses FOREIGN KEY (partner_id) REFERENCES business_partner(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'partner_address_countries' AND table_name = 'partner_address'
  ) THEN
    ALTER TABLE partner_address ADD CONSTRAINT partner_address_countries FOREIGN KEY (country) REFERENCES country(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'partner_address_states' AND table_name = 'partner_address'
  ) THEN
    ALTER TABLE partner_address ADD CONSTRAINT partner_address_states FOREIGN KEY (country, state) REFERENCES state(country_id, id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'partner_domains' AND table_name = 'partner_domain'
  ) THEN
    ALTER TABLE partner_domain ADD CONSTRAINT partner_domains FOREIGN KEY (partner_id) REFERENCES business_partner(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'user_refresh_tokens' AND table_name = 'user_refresh_token'
  ) THEN
    ALTER TABLE user_refresh_token ADD CONSTRAINT user_refresh_tokens FOREIGN KEY (user_id) REFERENCES user_account(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'user_trusted_devices' AND table_name = 'user_trusted_device'
  ) THEN
    ALTER TABLE user_trusted_device ADD CONSTRAINT user_trusted_devices FOREIGN KEY (user_id) REFERENCES user_account(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'api_key_partners' AND table_name = 'api_key'
  ) THEN
    ALTER TABLE api_key ADD CONSTRAINT api_key_partners FOREIGN KEY (partner_id) REFERENCES business_partner(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'api_key_users' AND table_name = 'api_key'
  ) THEN
    ALTER TABLE api_key ADD CONSTRAINT api_key_users FOREIGN KEY (user_id) REFERENCES user_account(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'user_otps' AND table_name = 'user_otp'
  ) THEN
    ALTER TABLE user_otp ADD CONSTRAINT user_otps FOREIGN KEY (user_id) REFERENCES user_account(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'user_social_providers' AND table_name = 'user_social_provider'
  ) THEN
    ALTER TABLE user_social_provider ADD CONSTRAINT user_social_providers FOREIGN KEY (user_id) REFERENCES user_account(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'consent_event_policies' AND table_name = 'consent_event'
  ) THEN
    ALTER TABLE consent_event ADD CONSTRAINT consent_event_policies FOREIGN KEY (policy_id) REFERENCES consent_policy(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'consent_event_users' AND table_name = 'consent_event'
  ) THEN
    ALTER TABLE consent_event ADD CONSTRAINT consent_event_users FOREIGN KEY (user_id) REFERENCES user_account(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'device_token_users' AND table_name = 'device_token'
  ) THEN
    ALTER TABLE device_token ADD CONSTRAINT device_token_users FOREIGN KEY (user_id) REFERENCES user_account(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'oauth_authorization_code_user' AND table_name = 'oauth_authorization_code'
  ) THEN
    ALTER TABLE oauth_authorization_code ADD CONSTRAINT oauth_authorization_code_user FOREIGN KEY (user_id) REFERENCES user_account(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'oauth_authorization_code_client' AND table_name = 'oauth_authorization_code'
  ) THEN
    ALTER TABLE oauth_authorization_code ADD CONSTRAINT oauth_authorization_code_client FOREIGN KEY (client_id) REFERENCES oauth_client(client_id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'subscription_plan_prices' AND table_name = 'subscription_plan_price'
  ) THEN
    ALTER TABLE subscription_plan_price ADD CONSTRAINT subscription_plan_prices FOREIGN KEY (plan_id) REFERENCES subscription_plan(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'oauth_refresh_token_user' AND table_name = 'oauth_refresh_token'
  ) THEN
    ALTER TABLE oauth_refresh_token ADD CONSTRAINT oauth_refresh_token_user FOREIGN KEY (user_id) REFERENCES user_account(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'oauth_refresh_token_client' AND table_name = 'oauth_refresh_token'
  ) THEN
    ALTER TABLE oauth_refresh_token ADD CONSTRAINT oauth_refresh_token_client FOREIGN KEY (client_id) REFERENCES oauth_client(client_id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'subscription_quotas' AND table_name = 'subscription_quota'
  ) THEN
    ALTER TABLE subscription_quota ADD CONSTRAINT subscription_quotas FOREIGN KEY (plan_id) REFERENCES subscription_plan(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'sub_resources_quotas' AND table_name = 'subscription_quota'
  ) THEN
    ALTER TABLE subscription_quota ADD CONSTRAINT sub_resources_quotas FOREIGN KEY (resource_id) REFERENCES subscription_resource(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'partner_credential_partners' AND table_name = 'partner_credential'
  ) THEN
    ALTER TABLE partner_credential ADD CONSTRAINT partner_credential_partners FOREIGN KEY (partner_id) REFERENCES business_partner(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'partner_plan_subscriptions' AND table_name = 'partner_plan_subscription'
  ) THEN
    ALTER TABLE partner_plan_subscription ADD CONSTRAINT partner_plan_subscriptions FOREIGN KEY (partner_id) REFERENCES business_partner(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'partner_subscriptions_plan' AND table_name = 'partner_plan_subscription'
  ) THEN
    ALTER TABLE partner_plan_subscription ADD CONSTRAINT partner_subscriptions_plan FOREIGN KEY (plan_id) REFERENCES subscription_plan(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'partner_addon_subscriptions' AND table_name = 'partner_addon_subscription'
  ) THEN
    ALTER TABLE partner_addon_subscription ADD CONSTRAINT partner_addon_subscriptions FOREIGN KEY (partner_id) REFERENCES business_partner(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'partner_subscriptions_addon' AND table_name = 'partner_addon_subscription'
  ) THEN
    ALTER TABLE partner_addon_subscription ADD CONSTRAINT partner_subscriptions_addon FOREIGN KEY (addon_id) REFERENCES subscription_addon(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'partner_usage_ledger' AND table_name = 'usage_ledger'
  ) THEN
    ALTER TABLE usage_ledger ADD CONSTRAINT partner_usage_ledger FOREIGN KEY (partner_id) REFERENCES business_partner(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'partner_payment_methods' AND table_name = 'payment_method'
  ) THEN
    ALTER TABLE payment_method ADD CONSTRAINT partner_payment_methods FOREIGN KEY (partner_id) REFERENCES business_partner(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'user_bank_info_users' AND table_name = 'user_bank_info'
  ) THEN
    ALTER TABLE user_bank_info ADD CONSTRAINT user_bank_info_users FOREIGN KEY (user_id) REFERENCES user_account(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'user_bank_info_partners' AND table_name = 'user_bank_info'
  ) THEN
    ALTER TABLE user_bank_info ADD CONSTRAINT user_bank_info_partners FOREIGN KEY (partner_id) REFERENCES business_partner(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'user_payment_method_users' AND table_name = 'user_payment_method'
  ) THEN
    ALTER TABLE user_payment_method ADD CONSTRAINT user_payment_method_users FOREIGN KEY (user_id) REFERENCES user_account(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'partner_invoices' AND table_name = 'invoice'
  ) THEN
    ALTER TABLE invoice ADD CONSTRAINT partner_invoices FOREIGN KEY (partner_id) REFERENCES business_partner(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'invoice_lines' AND table_name = 'invoice_line'
  ) THEN
    ALTER TABLE invoice_line ADD CONSTRAINT invoice_lines FOREIGN KEY (invoice_id) REFERENCES invoice(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'partner_billing_customers' AND table_name = 'partner_billing_customer'
  ) THEN
    ALTER TABLE partner_billing_customer ADD CONSTRAINT partner_billing_customers FOREIGN KEY (partner_id) REFERENCES business_partner(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'subscription_invoice_lines' AND table_name = 'subscription_invoice_line'
  ) THEN
    ALTER TABLE subscription_invoice_line ADD CONSTRAINT subscription_invoice_lines FOREIGN KEY (invoice_id, invoice_line_seq) REFERENCES invoice_line(invoice_id, seq);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'subscription_invoice_line_plans' AND table_name = 'subscription_invoice_line'
  ) THEN
    ALTER TABLE subscription_invoice_line ADD CONSTRAINT subscription_invoice_line_plans FOREIGN KEY (plan_id) REFERENCES subscription_plan(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'subscription_invoice_line_addons' AND table_name = 'subscription_invoice_line'
  ) THEN
    ALTER TABLE subscription_invoice_line ADD CONSTRAINT subscription_invoice_line_addons FOREIGN KEY (addon_id) REFERENCES subscription_addon(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'partner_payment_records' AND table_name = 'payment_record'
  ) THEN
    ALTER TABLE payment_record ADD CONSTRAINT partner_payment_records FOREIGN KEY (partner_id) REFERENCES business_partner(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'invoice_payment_records' AND table_name = 'payment_record'
  ) THEN
    ALTER TABLE payment_record ADD CONSTRAINT invoice_payment_records FOREIGN KEY (invoice_id) REFERENCES invoice(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'payment_record_invoice_partner' AND table_name = 'payment_record'
  ) THEN
    ALTER TABLE payment_record ADD CONSTRAINT payment_record_invoice_partner FOREIGN KEY (invoice_id, partner_id) REFERENCES invoice(id, partner_id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'payment_record_invoice_currency' AND table_name = 'payment_record'
  ) THEN
    ALTER TABLE payment_record ADD CONSTRAINT payment_record_invoice_currency FOREIGN KEY (invoice_id, currency) REFERENCES invoice(id, currency);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'payment_allocations' AND table_name = 'invoice_line_payment'
  ) THEN
    ALTER TABLE invoice_line_payment ADD CONSTRAINT payment_allocations FOREIGN KEY (payment_record_id, invoice_id) REFERENCES payment_record(id, invoice_id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'invoice_line_allocations' AND table_name = 'invoice_line_payment'
  ) THEN
    ALTER TABLE invoice_line_payment ADD CONSTRAINT invoice_line_allocations FOREIGN KEY (invoice_id, invoice_line_seq) REFERENCES invoice_line(invoice_id, seq);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'outbox_event_partner' AND table_name = 'outbox_event'
  ) THEN
    ALTER TABLE outbox_event ADD CONSTRAINT outbox_event_partner FOREIGN KEY (partner_id) REFERENCES business_partner(id) ON DELETE SET NULL;
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'application_config_values' AND table_name = 'application_config_value'
  ) THEN
    ALTER TABLE application_config_value ADD CONSTRAINT application_config_values FOREIGN KEY (flag_id) REFERENCES application_config_flag(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'agency_profile_partner' AND table_name = 'agency_profile'
  ) THEN
    ALTER TABLE agency_profile ADD CONSTRAINT agency_profile_partner FOREIGN KEY (agency_partner_id) REFERENCES business_partner(id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'invitation_agency' AND table_name = 'agency_client_invitation'
  ) THEN
    ALTER TABLE agency_client_invitation ADD CONSTRAINT invitation_agency FOREIGN KEY (agency_partner_id) REFERENCES agency_profile(agency_partner_id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'invitation_client' AND table_name = 'agency_client_invitation'
  ) THEN
    ALTER TABLE agency_client_invitation ADD CONSTRAINT invitation_client FOREIGN KEY (client_partner_id) REFERENCES business_partner(id) ON DELETE SET NULL;
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'invitation_accepted_by' AND table_name = 'agency_client_invitation'
  ) THEN
    ALTER TABLE agency_client_invitation ADD CONSTRAINT invitation_accepted_by FOREIGN KEY (accepted_by) REFERENCES user_account(id) ON DELETE SET NULL;
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'delegation_client' AND table_name = 'agency_client_delegation'
  ) THEN
    ALTER TABLE agency_client_delegation ADD CONSTRAINT delegation_client FOREIGN KEY (client_partner_id) REFERENCES business_partner(id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'delegation_agency' AND table_name = 'agency_client_delegation'
  ) THEN
    ALTER TABLE agency_client_delegation ADD CONSTRAINT delegation_agency FOREIGN KEY (agency_partner_id) REFERENCES agency_profile(agency_partner_id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'delegation_grantor' AND table_name = 'agency_client_delegation'
  ) THEN
    ALTER TABLE agency_client_delegation ADD CONSTRAINT delegation_grantor FOREIGN KEY (granted_by) REFERENCES user_account(id) ON DELETE RESTRICT;
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'delegation_revoker' AND table_name = 'agency_client_delegation'
  ) THEN
    ALTER TABLE agency_client_delegation ADD CONSTRAINT delegation_revoker FOREIGN KEY (revoked_by) REFERENCES user_account(id) ON DELETE RESTRICT;
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'client_billing_delegation' AND table_name = 'agency_client_billing'
  ) THEN
    ALTER TABLE agency_client_billing ADD CONSTRAINT client_billing_delegation FOREIGN KEY (client_delegation_id) REFERENCES agency_client_delegation(id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'agency_payout_profile_agency' AND table_name = 'agency_payout_profile'
  ) THEN
    ALTER TABLE agency_payout_profile ADD CONSTRAINT agency_payout_profile_agency FOREIGN KEY (agency_partner_id) REFERENCES agency_profile(agency_partner_id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'agency_payout_profile_bank_info' AND table_name = 'agency_payout_profile'
  ) THEN
    ALTER TABLE agency_payout_profile ADD CONSTRAINT agency_payout_profile_bank_info FOREIGN KEY (user_bank_info_id, agency_partner_id) REFERENCES user_bank_info(id, partner_id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'client_rate_agency' AND table_name = 'agency_client_rate'
  ) THEN
    ALTER TABLE agency_client_rate ADD CONSTRAINT client_rate_agency FOREIGN KEY (agency_partner_id) REFERENCES agency_profile(agency_partner_id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'client_rate_client' AND table_name = 'agency_client_rate'
  ) THEN
    ALTER TABLE agency_client_rate ADD CONSTRAINT client_rate_client FOREIGN KEY (client_partner_id) REFERENCES business_partner(id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'commission_client_billing' AND table_name = 'agency_commission'
  ) THEN
    ALTER TABLE agency_commission ADD CONSTRAINT commission_client_billing FOREIGN KEY (client_billing_id) REFERENCES agency_client_billing(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'commission_source_allocation' AND table_name = 'agency_commission'
  ) THEN
    ALTER TABLE agency_commission ADD CONSTRAINT commission_source_allocation FOREIGN KEY (invoice_line_payment_id) REFERENCES invoice_line_payment(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'commission_reversal_of' AND table_name = 'agency_commission'
  ) THEN
    ALTER TABLE agency_commission ADD CONSTRAINT commission_reversal_of FOREIGN KEY (reversal_of_id) REFERENCES agency_commission(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'payout_agency' AND table_name = 'agency_payout'
  ) THEN
    ALTER TABLE agency_payout ADD CONSTRAINT payout_agency FOREIGN KEY (agency_partner_id) REFERENCES agency_profile(agency_partner_id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'payout_destination_version' AND table_name = 'agency_payout'
  ) THEN
    ALTER TABLE agency_payout ADD CONSTRAINT payout_destination_version FOREIGN KEY (user_bank_info_id, agency_partner_id) REFERENCES user_bank_info(id, partner_id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'payout_lines' AND table_name = 'agency_payout_line'
  ) THEN
    ALTER TABLE agency_payout_line ADD CONSTRAINT payout_lines FOREIGN KEY (payout_id) REFERENCES agency_payout(id);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
     WHERE constraint_name = 'payout_line_commission' AND table_name = 'agency_payout_line'
  ) THEN
    ALTER TABLE agency_payout_line ADD CONSTRAINT payout_line_commission FOREIGN KEY (commission_id) REFERENCES agency_commission(id);
  END IF;
END $$;
