package schema

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// SeedFile represents seed data for multiple tables.
type SeedFile struct {
	Comment string       `yaml:"comment,omitempty"`
	Order   int          `yaml:"order,omitempty"`
	Seeds   []*SeedTable `yaml:"seeds"`
}

// SeedTable represents INSERT data for a single table.
type SeedTable struct {
	Table   string           `yaml:"table"`
	Columns []string         `yaml:"columns"`
	Rows    [][]any          `yaml:"rows"`
}

// ParseSeedFile parses a single seed YAML file.
func ParseSeedFile(path string) (*SeedFile, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("failed to read %s: %w", path, err)
	}
	var sf SeedFile
	if err := yaml.Unmarshal(data, &sf); err != nil {
		return nil, fmt.Errorf("failed to parse %s: %w", path, err)
	}
	return &sf, nil
}

// ParseSeedDir parses all seed YAML files in a directory.
func ParseSeedDir(dir string) ([]*SeedFile, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("failed to read directory %s: %w", dir, err)
	}
	var seeds []*SeedFile
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		ext := filepath.Ext(entry.Name())
		if ext != ".yml" && ext != ".yaml" {
			continue
		}
		if !strings.Contains(entry.Name(), "seed") {
			continue
		}
		sf, err := ParseSeedFile(filepath.Join(dir, entry.Name()))
		if err != nil {
			return nil, err
		}
		seeds = append(seeds, sf)
	}
	sort.Slice(seeds, func(i, j int) bool {
		return seeds[i].Order < seeds[j].Order
	})
	return seeds, nil
}

// GenerateSeedSQL produces INSERT statements for all seed data.
// It groups rows by table and orders tables using the schema's foreign key
// graph (topological sort) so that referenced rows are inserted first.
func GenerateSeedSQL(seeds []*SeedFile, s *Schema) string {
	// Collect all seed entries grouped by table, preserving row order.
	type tableInsert struct {
		Columns []string
		Rows    [][]any
	}
	grouped := make(map[string]*tableInsert)
	var tableOrder []string // tracks first-seen order as fallback
	for _, sf := range seeds {
		for _, st := range sf.Seeds {
			ti, exists := grouped[st.Table]
			if !exists {
				ti = &tableInsert{Columns: st.Columns}
				grouped[st.Table] = ti
				tableOrder = append(tableOrder, st.Table)
			}
			ti.Rows = append(ti.Rows, st.Rows...)
		}
	}

	// Build FK-safe table order via topological sort from the schema.
	sortedTables := topoSortTables(s)
	// Filter to only tables that have seed data, preserving topo order.
	var orderedNames []string
	seen := make(map[string]bool)
	for _, name := range sortedTables {
		if _, ok := grouped[name]; ok {
			orderedNames = append(orderedNames, name)
			seen[name] = true
		}
	}
	// Append any seed tables not found in the schema (safety fallback).
	for _, name := range tableOrder {
		if !seen[name] {
			orderedNames = append(orderedNames, name)
		}
	}

	var sb strings.Builder
	sb.WriteString("-- ==========================================================================\n")
	sb.WriteString("-- Seed data — generated by schemagen\n")
	sb.WriteString("-- ==========================================================================\n\n")
	// P1-53: wrap the entire seed batch in a transaction so a row
	// failure mid-way doesn't leave the DB partially populated.
	// `ON CONFLICT DO NOTHING` makes individual rows re-runnable;
	// the surrounding BEGIN/COMMIT bounds the all-or-nothing
	// semantics for new installs.
	sb.WriteString("BEGIN;\n\n")

	for _, tableName := range orderedNames {
		ti := grouped[tableName]
		cols := strings.Join(ti.Columns, ", ")
		for _, row := range ti.Rows {
			vals := make([]string, len(row))
			for i, v := range row {
				vals[i] = formatSeedValue(v)
			}
			sb.WriteString(fmt.Sprintf("INSERT INTO %s (%s) VALUES (%s) ON CONFLICT DO NOTHING;\n",
				tableName, cols, strings.Join(vals, ", ")))
		}
		sb.WriteString("\n")
	}
	sb.WriteString("COMMIT;\n")
	return sb.String()
}

// topoSortTables returns table names in FK-safe insertion order using Kahn's algorithm.
func topoSortTables(s *Schema) []string {
	if s == nil {
		return nil
	}
	// Build adjacency: if table A has FK referencing table B, then B must come before A.
	inDegree := make(map[string]int)
	deps := make(map[string][]string) // deps[B] = tables that depend on B
	for _, t := range s.Tables {
		inDegree[t.Name] = inDegree[t.Name] // ensure entry exists
		for _, fk := range t.ForeignKeys {
			ref := fk.References.Table
			if ref == t.Name {
				continue // self-reference
			}
			inDegree[ref] = inDegree[ref] // ensure entry exists
			deps[ref] = append(deps[ref], t.Name)
			inDegree[t.Name]++
		}
	}

	// Kahn's algorithm — use schema Order for stable tie-breaking.
	orderMap := make(map[string]int)
	for _, t := range s.Tables {
		orderMap[t.Name] = t.Order
	}

	var queue []string
	for name, deg := range inDegree {
		if deg == 0 {
			queue = append(queue, name)
		}
	}
	sort.Slice(queue, func(i, j int) bool {
		return orderMap[queue[i]] < orderMap[queue[j]]
	})

	var result []string
	for len(queue) > 0 {
		node := queue[0]
		queue = queue[1:]
		result = append(result, node)
		for _, dep := range deps[node] {
			inDegree[dep]--
			if inDegree[dep] == 0 {
				queue = append(queue, dep)
			}
		}
		// Re-sort for stable output when new nodes become available.
		sort.Slice(queue, func(i, j int) bool {
			return orderMap[queue[i]] < orderMap[queue[j]]
		})
	}
	return result
}

func formatSeedValue(v any) string {
	if v == nil {
		return "NULL"
	}
	switch val := v.(type) {
	case bool:
		if val {
			return "TRUE"
		}
		return "FALSE"
	case int:
		return fmt.Sprintf("%d", val)
	case float64:
		if val == float64(int64(val)) {
			return fmt.Sprintf("%d", int64(val))
		}
		return fmt.Sprintf("%g", val)
	case string:
		return "'" + strings.ReplaceAll(val, "'", "''") + "'"
	default:
		// Apply the same single-quote escape to the fallback `%v`
		// rendering so a YAML value of an unrecognized type (slice,
		// map, custom struct) cannot smuggle a quote through (P1-52).
		rendered := fmt.Sprintf("%v", val)
		return "'" + strings.ReplaceAll(rendered, "'", "''") + "'"
	}
}
