package pgsql

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/nauticana/keel/common"
	"github.com/nauticana/keel/data"
	"github.com/nauticana/keel/model"
	"github.com/nauticana/keel/port"
	"github.com/nauticana/keel/secret"
)

const (
	IT_TEXT     = "text"
	IT_TEXTAREA = "textarea"
	IT_NUMBER   = "number"
	IT_CHECKBOX = "checkbox"
	IT_DATETIME = "datetime-local"
	IT_SELECT   = "select"
)

// pgsqlMetaQueries returns the information_schema lookups parameterized
// by the configured search-path schema. Schema name flows in via a
// SQL placeholder rather than fmt.Sprintf string interpolation
// (P1-42) — so a schema flag value with an embedded apostrophe can't
// produce malformed SQL or, in extreme cases, smuggle a query.
func pgsqlMetaQueries(_ string) map[string]string {
	return map[string]string{
		data.QGetColumns: `
SELECT b.table_name, b.column_name, b.udt_name, b.ordinal_position, b.is_nullable, b.character_maximum_length, b.numeric_precision, b.numeric_scale, b.column_default
  FROM information_schema.tables a, information_schema.columns b
 WHERE a.table_type = 'BASE TABLE'
   AND a.table_schema = ?
   AND b.table_schema = a.table_schema
   AND b.table_name = a.table_name
 ORDER BY b.table_name, b.ordinal_position`,

		data.QGetForeignKeys: `
SELECT distinct f.constraint_name, f.table_name, k.ordinal_position, k.column_name, c.table_name as parent_table
  FROM information_schema.key_column_usage k,
       information_schema.table_constraints f,
       information_schema.constraint_column_usage c
 WHERE f.constraint_type = 'FOREIGN KEY'
   AND f.table_schema    = ?
   AND k.constraint_name = f.constraint_name
   AND k.table_schema    = f.table_schema
   AND k.table_name      = f.table_name
   AND c.constraint_name = f.constraint_name
   AND c.table_schema    = f.table_schema
 ORDER BY 1,2,3`,

		data.QGetFkLookupStyles: `SELECT constraint_name, lookup_style FROM foreign_key_lookup`,

		data.QGetPrimaryKeys: `
SELECT p.table_name, k.ordinal_position, k.column_name
  FROM information_schema.table_constraints p,
       information_schema.key_column_usage k
 WHERE p.table_schema    = ?
   AND p.constraint_type = 'PRIMARY KEY'
   AND k.constraint_name = p.constraint_name
   AND k.table_schema    = p.table_schema
   AND k.table_name      = p.table_name
 ORDER BY 1,2`,

		data.QGetSequenceUsage: "select table_name, column_name, sequence_name from table_sequence_usage",
	}
}

type RepositoryPgsql struct {
	data.AbstractRepository
	Secrets secret.SecretProvider
	Client  *pgxpool.Pool
}

func (r *RepositoryPgsql) Connect(ctx context.Context) error {
	password, err := r.Secrets.GetSecret(ctx, *common.DBuser)
	if err != nil {
		return fmt.Errorf("failed to get secret: %w", err)
	}
	if password == "" {
		return fmt.Errorf("empty password read, database password is required for PostgreSQL")
	}
	// Build the DSN in pgx key-value form. URL form is fragile for passwords
	// containing :, /, @, ?, #, or , — pgx's URL parser treats a comma as a
	// multi-host separator, so a password generated by Secret Manager with
	// a comma in it parses as two hosts and the database name is lost.
	// Key-value form has no such ambiguity.
	parts := []string{
		"user=" + pgxKV(*common.DBuser),
		"password=" + pgxKV(password),
		"dbname=" + pgxKV(*common.DBname),
		"sslmode=" + pgxKV(*common.DBsslmode),
		"search_path=" + pgxKV(*common.DBschema),
	}
	if strings.HasPrefix(*common.DBhost, "/") {
		parts = append(parts, "host="+pgxKV(*common.DBhost))
	} else {
		parts = append(parts, "host="+pgxKV(*common.DBhost))
		parts = append(parts, fmt.Sprintf("port=%d", *common.DBport))
	}
	dsn := strings.Join(parts, " ")
	cfg, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		return fmt.Errorf("failed to parse postgres DSN: %w", err)
	}
	// P1-41: honor --db_pool_max. Previously declared but unused —
	// pgxpool would silently default to runtime.NumCPU() (or whatever
	// the SDK picks), which is the wrong sizing for a webserver
	// fronting a small DB.
	if max := *common.DBPoolMax; max > 0 {
		cfg.MaxConns = int32(max)
	}
	r.Client, err = pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		return fmt.Errorf("failed to connect to PostgreSQL: %w", err)
	}
	r.QuerySvc = &QueryServicePgsql{
		Client:      r.Client,
		Queries:     rewriteQueries(pgsqlMetaQueries(*common.DBschema)),
		IdGenerator: r.IdGenerator,
		// Some metaqueries take the schema as a bound argument.
		// Provided through a per-call wrapper rather than baked into
		// the SQL — see information_schema lookups above.
	}
	return nil
}

// pgxKV formats a value for pgx's key-value DSN. pgx treats single
// quotes as value delimiters, backslashes as escape characters, and
// splits keys from values on `=` while splitting key=value pairs on
// whitespace. Values without ANY of those metacharacters pass through
// raw (no URL-encoding); anything else gets single-quoted with `'`
// and `\` escaped.
//
// `=` was missing from the trigger set previously (MAJOR 12). A
// password containing `=` (no whitespace, no quote, no backslash)
// would pass through raw and combine with the next key — so a value
// like `pa=ss` would produce `password=pa=ss dbname=...`, which pgx
// parses as `password=pa` followed by an unrelated `ss` key →
// malformed DSN.
func pgxKV(v string) string {
	if !strings.ContainsAny(v, " \t\n'\\=") {
		return v
	}
	var b strings.Builder
	b.WriteByte('\'')
	for _, ch := range v {
		if ch == '\'' || ch == '\\' {
			b.WriteByte('\\')
		}
		b.WriteRune(ch)
	}
	b.WriteByte('\'')
	return b.String()
}

func (r *RepositoryPgsql) GetQueryService(ctx context.Context, queries map[string]string) data.QueryService {
	return &QueryServicePgsql{
		Client:      r.Client,
		Queries:     rewriteQueries(queries),
		IdGenerator: r.IdGenerator,
	}
}

func (r *RepositoryPgsql) BeginTx(ctx context.Context, queries map[string]string) (data.TxQueryService, error) {
	tx, err := r.Client.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to begin transaction: %w", err)
	}
	return &TxQueryServicePgsql{
		Tx:          tx,
		Queries:     rewriteQueries(queries),
		IdGenerator: r.IdGenerator,
	}, nil
}

// rewriteQueries converts the keel-canonical `?` placeholder style
// to PostgreSQL's `$1`, `$2`, ... style across an entire query map.
// Shared between GetQueryService and BeginTx so the two paths can
// never drift on placeholder semantics.
func rewriteQueries(in map[string]string) map[string]string {
	out := make(map[string]string, len(in))
	for k, v := range in {
		out[k] = rewritePlaceholders(v)
	}
	return out
}

// rewritePlaceholders walks a SQL string and converts each `?` outside
// of string-literals / comments into a positional `$N` placeholder.
// The state machine tracks every context where `?` is literal text:
// single-quoted strings (with `”` escape), double-quoted identifiers,
// `-- line` comments, `/* block */` comments WITH NESTING (Postgres
// allows nested block comments), and `$tag$ ... $tag$` dollar-quoted
// strings (used by `CREATE FUNCTION ... AS $$...$$` and friends).
//
// Without the dollar-quote and nesting handling (MAJOR 10), a future
// consumer registering a SQL function body containing `?` characters
// would silently see them renumbered as placeholders.
func rewritePlaceholders(sql string) string {
	var b strings.Builder
	b.Grow(len(sql))
	n := 0
	const (
		stCode = iota
		stSingle
		stDouble
		stLineComment
		stBlockComment
		stDollar
	)
	state := stCode
	blockDepth := 0
	dollarTag := ""
	for i := 0; i < len(sql); i++ {
		ch := sql[i]
		switch state {
		case stCode:
			switch {
			case ch == '\'':
				state = stSingle
				b.WriteByte(ch)
			case ch == '"':
				state = stDouble
				b.WriteByte(ch)
			case ch == '-' && i+1 < len(sql) && sql[i+1] == '-':
				state = stLineComment
				b.WriteByte(ch)
			case ch == '/' && i+1 < len(sql) && sql[i+1] == '*':
				state = stBlockComment
				blockDepth = 1
				b.WriteByte(ch)
			case ch == '$':
				// Try to recognize a dollar-quote opening tag:
				// `$tag$` or `$$`. If the next `$` doesn't appear
				// within a small window of valid tag characters,
				// treat the `$` as ordinary code (could be a `$N`
				// placeholder we ourselves emit, or part of a
				// type cast like `'5'::numeric$`).
				if tag, ok := readDollarTag(sql, i); ok {
					state = stDollar
					dollarTag = tag
					b.WriteString(tag)
					i += len(tag) - 1
				} else {
					b.WriteByte(ch)
				}
			case ch == '?':
				n++
				fmt.Fprintf(&b, "$%d", n)
			default:
				b.WriteByte(ch)
			}
		case stSingle:
			b.WriteByte(ch)
			if ch == '\'' {
				// Doubled '' is an escaped single-quote inside a
				// SQL string literal — stay in stSingle.
				if i+1 < len(sql) && sql[i+1] == '\'' {
					i++
					b.WriteByte(sql[i])
					continue
				}
				state = stCode
			}
		case stDouble:
			b.WriteByte(ch)
			if ch == '"' {
				state = stCode
			}
		case stLineComment:
			b.WriteByte(ch)
			if ch == '\n' {
				state = stCode
			}
		case stBlockComment:
			b.WriteByte(ch)
			// Postgres allows nested /* ... */ — track depth so
			// the outer close doesn't fire on an inner */.
			if ch == '/' && i+1 < len(sql) && sql[i+1] == '*' {
				blockDepth++
				i++
				b.WriteByte(sql[i])
			} else if ch == '*' && i+1 < len(sql) && sql[i+1] == '/' {
				i++
				b.WriteByte(sql[i])
				blockDepth--
				if blockDepth == 0 {
					state = stCode
				}
			}
		case stDollar:
			b.WriteByte(ch)
			// Look for the closing tag (must match opening exactly).
			if ch == '$' && strings.HasPrefix(sql[i:], dollarTag) {
				// We already wrote the leading `$`; write the rest
				// of the tag and advance.
				rest := dollarTag[1:]
				b.WriteString(rest)
				i += len(rest)
				state = stCode
				dollarTag = ""
			}
		}
	}
	return b.String()
}

// readDollarTag attempts to recognize a Postgres dollar-quote tag
// starting at sql[i] (which is '$'). Returns the full tag including
// both `$` delimiters and ok=true on a match, or ("", false) when
// the run isn't a valid tag (no closing `$` within the small
// identifier window).
func readDollarTag(sql string, i int) (string, bool) {
	if i >= len(sql) || sql[i] != '$' {
		return "", false
	}
	// `$$` is the empty-tag form.
	if i+1 < len(sql) && sql[i+1] == '$' {
		return "$$", true
	}
	// `$identifier$` — identifier is letters / digits / underscore.
	for j := i + 1; j < len(sql) && j-i <= 64; j++ {
		ch := sql[j]
		if ch == '$' {
			return sql[i : j+1], true
		}
		if !(ch == '_' ||
			(ch >= 'a' && ch <= 'z') ||
			(ch >= 'A' && ch <= 'Z') ||
			(ch >= '0' && ch <= '9')) {
			return "", false
		}
	}
	return "", false
}

func (r *RepositoryPgsql) CreateTableService(ctx context.Context, table *model.TableDefinition) data.TableService {
	if r.TableServices[table.TableName] != nil {
		return r.TableServices[table.TableName]
	}
	return &TableServicePgsql{
		AbstractTableService: data.AbstractTableService{
			Table:       table,
			AuthQuery:   r.GetQueryService(ctx, data.AuthorizationQueries),
			IdGenerator: r.IdGenerator,
		},
		Schema: *common.DBschema,
		Client: r.Client,
	}
}

// RunInTx runs fn inside a Postgres transaction. The TxView passed to
// fn yields tx-bound copies of every TableService registered on the
// repository, so multi-table writes (RelationAPI.Post's parent +
// children batch) all land in the same transaction.
//
// Commits on a nil return; rolls back on any error or panic. The
// rollback path uses a fresh background context so a parent-context
// cancellation during fn doesn't also block the rollback itself.
func (r *RepositoryPgsql) RunInTx(ctx context.Context, fn func(view data.TxView) error) (err error) {
	tx, err := r.Client.Begin(ctx)
	if err != nil {
		return fmt.Errorf("pgsql: begin tx: %w", err)
	}
	defer func() {
		if rec := recover(); rec != nil {
			rbCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
			defer cancel()
			_ = tx.Rollback(rbCtx)
			panic(rec)
		}
	}()
	view := &pgsqlTxView{tx: tx, repo: r}
	if err := fn(view); err != nil {
		rbCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		if rbErr := tx.Rollback(rbCtx); rbErr != nil && rbErr != pgx.ErrTxClosed {
			return fmt.Errorf("pgsql: tx rollback after %v: %w", err, rbErr)
		}
		return err
	}
	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("pgsql: commit tx: %w", err)
	}
	return nil
}

func parseColumnDefault(raw string) string {
	s := strings.TrimSpace(raw)
	if idx := strings.Index(s, "::"); idx > 0 {
		s = s[:idx]
	}
	s = strings.Trim(s, "'")
	return s
}

func (r *RepositoryPgsql) LoadColumns(ctx context.Context) (map[string][]*model.TableColumn, error) {
	result := make(map[string][]*model.TableColumn)
	res, err := r.QuerySvc.Query(ctx, data.QGetColumns, *common.DBschema)
	if err != nil {
		return nil, fmt.Errorf("failed to load columns: %w", err)
	}

	for _, rec := range res.Rows {
		tableName := strings.ToLower(common.AsString(rec[0]))
		columnName := strings.ToLower(common.AsString(rec[1]))
		dataType := strings.ToLower(common.AsString(rec[2]))
		position := common.AsInt32(rec[3])
		required := strings.ToLower(common.AsString(rec[4])) == "false"
		size := common.AsInt32(rec[5])
		precision := common.AsInt32(rec[6])
		scale := common.AsInt32(rec[7])
		columnDefault := common.AsString(rec[8])
		if int(precision) > 0 {
			size = precision
		}
		col := &model.TableColumn{
			ColumnName: columnName,
			PascalName: common.PascalCase(columnName),
			Caption:    common.TitleCase(columnName),
			Required:   required,
			Size:       int(size),
			Scale:      int(scale),
			Order:      int(position),
		}
		if columnDefault != "" && !strings.HasPrefix(columnDefault, "nextval(") {
			col.HasDefault = true
			col.DefaultValue = parseColumnDefault(columnDefault)
		}
		switch dataType {
		case "nvarchar", "varchar", "char", "bpchar":
			col.DataType = model.DT_STRING
			col.InputType = IT_TEXT
		case "text":
			col.DataType = model.DT_STRING
			col.InputType = IT_TEXTAREA
			col.Size = 4000
		case "int2":
			col.DataType = model.DT_INT
			col.InputType = IT_NUMBER
			col.Size = 5
			col.Step = "1"
		case "int4":
			col.DataType = model.DT_INT
			col.InputType = IT_NUMBER
			col.Size = 9
			col.Step = "1"
		case "int8":
			col.DataType = model.DT_INT
			col.InputType = IT_NUMBER
			col.Size = 18
			col.Step = "1"
		case "decimal", "numeric", "float", "float8", "double":
			col.DataType = model.DT_FLOAT
			col.InputType = IT_NUMBER
			if col.Scale > 0 {
				col.Step = "0." + strings.Repeat("0", int(col.Scale)-1) + "1"
			} else {
				col.Step = "1"
			}
		case "bool", "boolean":
			col.DataType = model.DT_BOOL
			col.InputType = IT_CHECKBOX
		case "timestamp", "date", "time", "datetime":
			col.DataType = model.DT_TIME
			col.InputType = IT_DATETIME
		default:
			col.DataType = model.DT_STRING
			col.InputType = IT_TEXT
		}
		if col.Order == 1 {
			result[tableName] = []*model.TableColumn{col}
		} else {
			result[tableName] = append(result[tableName], col)
		}
	}

	seq, err := r.QuerySvc.Query(ctx, data.QGetSequenceUsage)
	if err != nil {
		return nil, fmt.Errorf("failed to load sequence: %w", err)
	}
	for _, rec := range seq.Rows {
		tableName := strings.ToLower(common.AsString(rec[0]))
		columnName := strings.ToLower(common.AsString(rec[1]))
		sequenceName := strings.ToLower(common.AsString(rec[2]))
		columns := result[tableName]
		for _, col := range columns {
			if col.ColumnName == columnName {
				col.SequenceName = sequenceName
				break
			}
		}
	}
	return result, nil
}

func NewPgSQLDatabase(ctx context.Context, secretProvider secret.SecretProvider, idGenerator port.BigintGenerator) (data.DatabaseRepository, error) {
	repoOLTP := &RepositoryPgsql{
		Secrets: secretProvider,
	}
	repoOLTP.AbstractRepository = data.AbstractRepository{
		IdGenerator: idGenerator,
		ConnectFn: func(ctx context.Context) error {
			return repoOLTP.Connect(ctx)
		},
		LoadColumnsFn: func(ctx context.Context) (map[string][]*model.TableColumn, error) {
			return repoOLTP.LoadColumns(ctx)
		},
		CreateTableSvcFn: func(ctx context.Context, table *model.TableDefinition) data.TableService {
			return repoOLTP.CreateTableService(ctx, table)
		},
	}
	if err := repoOLTP.Init(ctx); err != nil {
		return nil, err
	}
	return repoOLTP, nil
}
